function scr_sprite_get_constant(argument0) {
	if (global.apariencia == 0)
	{
	    switch argument0
	    {
	        case spr_SMB_mushroom:
	            return 1;
			case spr_SMB2_mushroom:
	            return -80;
	        case spr_SMB_fireflower:
	            return 2;
	        case spr_SMB_superflower:
	            return -50;
	        case spr_SMB_megamushroom:
	            return -77;
	        case spr_SMB_hen_mushroom:
	            return -78;
	        case spr_SMB_link:
	            return -85;
	        case spr_SMB3_hammersuit:
	            return -78;
	        case spr_NSMBU_superacorn:
	            return -78;
	        case spr_pballon:
	            return -78;
	        case spr_SMB_koopa:
	            return -31;
            case spr_SMB_koopa_b:
                return -90;
            case spr_SMB_koopa_red_b:
                return -91;
	        case spr_SMB_shell_drybones:
	            return -81;
	        case spr_SMB_1up:
	            return -18;
	        case spr_rotten_b:
	            return -18;
	        case spr_SMB_star:
	            return -21;
	        case spr_SMB_coin:
	            return -1;
	        case spr_SMB_key:
	            return -22;
	        case spr_SMB_pink_coin:
	            return -76;
	        case spr_SMB_spring:
	            return -23;
	        case spr_SMB_pswitch:
	            return -25;
	        case spr_SMB_vine_green:
	            return -28;
	        case spr_SMB_koopa_red:
	            return -32;
	        case spr_SMB_spiny:
	            return -33;
	        case spr_SMB_buzzybeetle:
	            return -34;
	        case spr_SMB_buzzybeetle_night:
	            return -34;
	        case spr_SMB_cheepcheep:
	            return -54;
	        case spr_SMB_cheepcheep2:
	            return -79;
	        case spr_SMB_goomba:
	            return -55;
	        case spr_SMB_goomba2:
	            return -56;
	        case spr_SMB_bobomb:
	            return -57;
	        case spr_SMB_bobomb_night:
	            return -57;
	        case spr_SMB_bobomb_ready:
	            return -58;
	        case spr_SMB_hammerbro:
	            return -59;
	        case spr_SMB_boo:
	            return -60;
	        case spr_SMB_muncher:
	            return -61;
	        case spr_SMB_muncher_night:
	            return -61;
	        case spr_SMB_montymole:
	            return -62;
	        case spr_SMB_pplant:
	            return -63;
	        case spr_SMB_drybones:
	            return -64;
	        case spr_SMB_pow:
	            return -65;
	        case spr_SMB_spring_land:
	            return -66;
	        case spr_SMB_clown:
	            return -67;
	        case spr_SMB_clown_fire:
	            return -68;
	        case spr_SMB_shell_empty:
	            return -69;
	        case spr_SMB_shell_empty_night:
	            return -69;
	        case spr_SMB_shell_empty_spiny:
	            return -70;
	        case spr_SMB_podoboo:
	            return -73;
	        case spr_SMB_sledgebro:
	            return -72;
	        case spr_SMB_pplant_fire_down:
	            return -71;
	        case spr_SMB_goomba_shoe:
	            return -74;
	        case spr_SMB_goomba_shoe_red:
	            return -75;
	        case spr_SMB_waddlewing:
	            return -106;
	        default:
	            return -1;
	    }

	}
	else if (global.apariencia == 1)
	{
	    switch argument0
	    {
	        case spr_SMB3_mushroom:
	            return 1;
	        case spr_SMB3_fireflower:
	            return 2;
	        case spr_SMB2_mushroom:
	            return 1;
	        case spr_cap_res:
	            return 3;
	        case spr_pballon:
	            return -29;
	        case spr_NSMBU_superacorn:
	            return -29;
	        case spr_leaf:
	            return -39;
	        case spr_SMB_megamushroom_res:
	            return -39;
	        case spr_SMB_hen_mushroom:
	            return 1;
	        case spr_frogsuit:
	            return -29;
	        case spr_SMB3_hammersuit:
	            return -46;
	        case spr_SMB3_koopa:
	            return -31;
            case spr_SMB3_koopa_b:
                return -90;
            case spr_SMB3_koopa_red_b:
                return -91;
	        case spr_SMB3_shell_drybones:
	            return -81;
	        case spr_SMB3_1up:
	            return -18;
	        case spr_rotten_b:
	            return -18;
	        case spr_SMB3_star:
	            return -21;
	        case spr_SMB3_coin:
	            return -1;
	        case spr_SMB3_key:
	            return -22;
	        case spr_SMB3_pink_coin:
	            return -76;
	        case spr_SMB3_spring:
	            return -23;
	        case spr_SMB3_pswitch:
	            return -25;
	        case spr_SMB3_vine_green:
	            return -28;
	        case spr_SMB3_koopa_red:
	            return -32;
	        case spr_SMB3_spiny:
	            return -33;
	        case spr_SMB3_buzzybeetle:
	            return -34;
	        case spr_SMB3_buzzybeetle_night:
	            return -34;
	        case spr_SMB3_cheepcheep:
	            return -54;
	        case spr_SMB3_cheepcheep2:
	            return -79;
	        case spr_SMB3_goomba:
	            return -55;
	        case spr_SMB3_goomba2:
	            return -56;
	        case spr_SMB3_bobomb:
	            return -57;
	        case spr_SMB3_bobomb_night:
	            return -57;
	        case spr_SMB3_bobomb_ready:
	            return -58;
	        case spr_SMB3_hammerbro:
	            return -59;
	        case spr_SMB3_boo:
	            return -60;
	        case spr_SMB3_muncher:
	            return -61;
	        case spr_SMB3_muncher_night:
	            return -61;
	        case spr_SMB3_montymole:
	            return -62;
	        case spr_SMB3_pplant:
	            return -63;
	        case spr_SMB3_drybones:
	            return -64;
	        case spr_SMB3_pow:
	            return -65;
	        case spr_SMB3_spring_land:
	            return -66;
	        case spr_SMB3_clown:
	            return -67;
	        case spr_SMB3_clown_fire:
	            return -68;
	        case spr_SMB3_shell_empty:
	            return -69;
	        case spr_SMB3_shell_empty_night:
	            return -69;
	        case spr_SMB3_shell_spiny_empty:
	            return -70;
	        case spr_SMB3_podoboo:
	            return -73;
	        case spr_SMB3_sledgebro:
	            return -72;
	        case spr_SMB3_pplant_fire_down:
	            return -71;
	        case spr_SMB3_goomba_shoe:
	            return -74;
	        case spr_SMB3_goomba_shoe_red:
	            return -75;
	        case spr_SMB3_waddlewing:
	            return -106;
	        default:
	            return -1;
	    }
    
	}
	else if (global.apariencia == 2)
	{
	    switch argument0
	    {
	        case spr_mushroom:
	            return 1;
	        case spr_fireflower:
	            return 2;
	        case spr_SMB2_mushroom:
	            return 1;
	        case spr_cap:
	            return 3;
	        case spr_pballon:
	            return -82;
	        case spr_NSMBU_superacorn:
	            return -82;
	        case spr_SMB3_hammersuit:
	            return -82;
	        case spr_leaf:
	            return 3;
	        case spr_SMB_megamushroom_res:
	            return 3;
	        case spr_SMB_hen_mushroom:
	            return 1;
	        case spr_koopa:
	            return -31;
            case spr_koopa_b:
                return -90;
            case spr_koopa_red_b:
                return -91;
	        case spr_shell_drybones:
	            return -81;
	        case spr_1up:
	            return -18;
	        case spr_rotten_b:
	            return -18;
	        case spr_star:
	            return -21;
	        case spr_coin:
	            return -1;
	        case spr_key:
	            return -22;
	        case spr_pink_coin:
	            return -76;
	        case spr_spring:
	            return -23;
	        case spr_pswitch:
	            return -25;
	        case spr_vine_green:
	            return -28;
	        case spr_koopa_red:
	            return -32;
	        case spr_spiny:
	            return -33;
	        case spr_buzzybeetle:
	            return -34;
	        case spr_cheepcheep:
	            return -54;
	        case spr_cheepcheep2:
	            return -79;
	        case spr_galoomba:
	            return -55;
	        case spr_galoomba2:
	            return -56;
	        case spr_bobomb:
	            return -57;
	        case spr_bobomb_ready:
	            return -58;
	        case spr_hammerbro:
	            return -59;
	        case spr_boo:
	            return -60;
	        case spr_muncher:
	            return -61;
	        case spr_montymole:
	            return -62;
	        case spr_jumppiranha:
	            return -63;
	        case spr_drybones:
	            return -64;
	        case spr_block_pow:
	            return -65;
	        case spr_spring_land:
	            return -66;
	        case spr_clown:
	            return -67;
	        case spr_clown_fire:
	            return -68;
	        case spr_shell_buzzy_empty:
	            return -69;
	        case spr_shell_spiny_empty:
	            return -70;
	        case spr_podoboo:
	            return -73;
	        case spr_sledgebro:
	            return -72;
	        case spr_pplant_fire_down:
	            return -71;
	        case spr_egg:
	            return -74;
	        case spr_egg_red:
	            return -75;
	        case spr_waddlewing:
	            return -106;
	        default:
	            return -1;
	    }
    
	}
	else if (global.apariencia == 3)
	{
	    switch argument0
	    {
	        case spr_NSMBU_mushroom:
	            return 1;
	        case spr_NSMBU_fireflower:
	            return 2;
	        case spr_SMB2_mushroom:
	            return 1;
	        case spr_cap:
	            return -30;
	        case spr_SMB3_hammersuit:
	            return -38;
	        case spr_pballon:
	            return -43;
	        case spr_leaf:
	            return -30;
	        case spr_NSMBU_champicoptero:
	            return -30;
	        case spr_NSMBU_penguin:
	            return -38;
	        case spr_NSMBU_superacorn:
	            return -43;
	        case spr_SMB_megamushroom_res:
	            return -30;
	        case spr_SMB_hen_mushroom:
	            return 1;
	        case spr_NSMBU_koopa:
	            return -31;
            case spr_NSMBU_koopa_b:
                return -90;
            case spr_NSMBU_koopa_red_b:
                return -91;
	        case spr_NSMBU_shell_drybones:
	            return -81;
	        case spr_NSMBU_1up:
	            return -18;
	        case spr_rotten_b:
	            return -18;
	        case spr_NSMBU_star:
	            return -21;
	        case spr_NSMBU_coin:
	            return -1;
	        case spr_key:
	            return -22;
	        case spr_pink_coin:
	            return -76;
	        case spr_NSMBU_spring:
	            return -23;
	        case spr_NSMBU_pswitch:
	            return -25;
	        case spr_NSMBU_vine_green:
	            return -28;
	        case spr_koopa_red:
	            return -32;
	        case spr_NSMBU_spiny:
	            return -33;
	        case spr_NSMBU_buzzybeetle:
	            return -34;
	        case spr_NSMBU_cheepcheep:
	            return -54;
	        case spr_NSMBU_cheepcheep2:
	            return -79;
	        case spr_NSMBU_goomba:
	            return -55;
	        case spr_galoomba2:
	            return -56;
	        case spr_NSMBU_bobomb:
	            return -57;
	        case spr_bobomb_ready:
	            return -58;
	        case spr_hammerbro:
	            return -59;
	        case spr_NSMBU_boo_overworld:
	            return -60;
	        case spr_NSMBU_muncher:
	            return -61;
	        case spr_NSMBU_montymole:
	            return -62;
	        case spr_NSMBU_pplant:
	            return -63;
	        case spr_drybones:
	            return -64;
	        case spr_NSMBU_pow:
	            return -65;
	        case spr_spring_land:
	            return -66;
	        case spr_NSMBU_clown:
	            return -67;
	        case spr_NSMBU_clown_fire:
	            return -68;
	        case spr_shell_buzzy_empty:
	            return -69;
	        case spr_shell_spiny_empty:
	            return -70;
	        case spr_NSMBU_podoboo:
	            return -73;
	        case spr_sledgebro:
	            return -72;
	        case spr_pplant_fire_down:
	            return -71;
	        case spr_NSMBU_egg:
	            return -74;
	        case spr_egg_red:
	            return -75;
	        case spr_NSMBU_waddlewing:
	            return -106;
	        default:
	            return -1;
	    }
    
	}
	else if (global.apariencia == 4)
	{
	    switch argument0
	    {
	        case spr_SMB2_mushroom:
	            return 1;
	        case spr_SMB_fireflower:
	            return 2;
	        case spr_SMB_mushroom:
	            return -80;
	        case spr_SMB_superflower:
	            return -50;
	        case spr_SMB_megamushroom:
	            return -77;
	        case spr_SMB_hen_mushroom:
	            return -78;
	        case spr_SMB_link:
	            return -85;
	        case spr_SMB3_hammersuit:
	            return -78;
	        case spr_NSMBU_superacorn:
	            return -78;
	        case spr_pballon:
	            return -78;
	        case spr_SMB_koopa:
	            return -31;
	        case spr_SMB_shell_drybones:
	            return -81;
	        case spr_SMB_1up:
	            return -18;
	        case spr_rotten_b:
	            return -18;
	        case spr_SMB_star:
	            return -21;
	        case spr_SMB_coin:
	            return -1;
	        case spr_SMB_key:
	            return -22;
	        case spr_SMB_pink_coin:
	            return -76;
	        case spr_SMB_spring:
	            return -23;
	        case spr_SMB_pswitch:
	            return -25;
	        case spr_SMB_vine_green:
	            return -28;
	        case spr_SMB_koopa_red:
	            return -32;
	        case spr_SMB_spiny:
	            return -33;
	        case spr_SMB_buzzybeetle:
	            return -34;
	        case spr_SMB_buzzybeetle_night:
	            return -34;
	        case spr_SMB_cheepcheep:
	            return -54;
	        case spr_SMB_cheepcheep2:
	            return -79;
	        case spr_SMB_goomba:
	            return -55;
	        case spr_SMB_goomba2:
	            return -56;
	        case spr_SMB_bobomb:
	            return -57;
	        case spr_SMB_bobomb_night:
	            return -57;
	        case spr_SMB_bobomb_ready:
	            return -58;
	        case spr_SMB_hammerbro:
	            return -59;
	        case spr_SMB_boo:
	            return -60;
	        case spr_SMB_muncher:
	            return -61;
	        case spr_SMB_muncher_night:
	            return -61;
	        case spr_SMB_montymole:
	            return -62;
	        case spr_SMB_pplant:
	            return -63;
	        case spr_SMB_drybones:
	            return -64;
	        case spr_SMB_pow:
	            return -65;
	        case spr_SMB_spring_land:
	            return -66;
	        case spr_SMB_clown:
	            return -67;
	        case spr_SMB_clown_fire:
	            return -68;
	        case spr_SMB_shell_empty:
	            return -69;
	        case spr_SMB_shell_empty_night:
	            return -69;
	        case spr_SMB_shell_empty_spiny:
	            return -70;
	        case spr_SMB_podoboo:
	            return -73;
	        case spr_SMB_sledgebro:
	            return -72;
	        case spr_SMB_pplant_fire_down:
	            return -71;
	        case spr_SMB_goomba_shoe:
	            return -74;
	        case spr_SMB_goomba_shoe_red:
	            return -75;
	        default:
	            return -1;
	    }

	}


}
