function scr_constant_get_sprite(argument0) {
	if (global.apariencia == 0)
	{
	    switch argument0
	    {
	        case 1:
	            return spr_SMB_mushroom;
	        case 2:
	            return spr_SMB_fireflower;
	        case -50:
	            return spr_SMB_superflower;
	        case -80:
	            return spr_SMB2_mushroom;
	        case -77:
	            return spr_SMB_megamushroom;
	        case -85:
	            return spr_SMB_link;
	        case -78:
	            return spr_SMB_hen_mushroom;
	        case -30:
	            return spr_SMB_megamushroom;
	        case -46:
	            return spr_SMB_hen_mushroom;
	        case -43:
	            return spr_SMB_hen_mushroom;
	        case 3:
	            return spr_SMB_megamushroom;
	        case -82:
	            return spr_SMB_hen_mushroom;
	        case -39:
	            return spr_SMB_megamushroom;
	        case -29:
	            return spr_SMB_hen_mushroom;
	        case -38:
	            return spr_SMB_hen_mushroom;
	        case -81:
	            return spr_SMB_shell_drybones;
	        case -18:
	            if (global.bg_level == "ground" && global.modo_noche == 1)
	                return spr_rotten_b;
	            else
	                return spr_SMB_1up;
	        case -21:
	            return spr_SMB_star;
	        case -22:
	            return spr_SMB_key;
	        case -1:
	            return spr_SMB_coin;
	        case -76:
	            return spr_SMB_pink_coin;
	        case -23:
	            return spr_SMB_spring;
	        case -25:
	            return spr_SMB_pswitch;
	        case -28:
	            return spr_SMB_beanstalk;
	        case -31:
	            return spr_SMB_koopa;
	        case -90:
	            return spr_SMB_koopa_b;
	        case -32:
	            return spr_SMB_koopa_red;
	        case -91:
	            return spr_SMB_koopa_red_b;
	        case -33:
	            return spr_SMB_spiny;
	        case -34:
	            return spr_SMB_buzzybeetle;
	        case -54:
	            return spr_SMB_cheepcheep;
	        case -79:
	            return spr_SMB_cheepcheep2;
	        case -55:
	            return spr_SMB_goomba;
	        case -56:
	            return spr_SMB_goomba2;
	        case -57:
	            return spr_SMB_bobomb;
	        case -58:
	            return spr_SMB_bobomb_ready;
	        case -59:
	            return spr_SMB_hammerbro;
	        case -60:
	            return spr_SMB_boo;
	        case -61:
	            return spr_SMB_muncher;
	        case -62:
	            return spr_SMB_montymole;
	        case -63:
	            return spr_SMB_pplant;
	        case -64:
	            return spr_SMB_drybones;
	        case -65:
	            return spr_SMB_pow;
	        case -66:
	            return spr_SMB_spring_land;
	        case -67:
	            return spr_SMB_clown;
	        case -68:
	            return spr_SMB_clown_fire;
	        case -69:
	            if (global.bg_level == "castle" || global.bg_level == "ghost" || global.bg_level == "underground" || global.modo_noche == 1)
	                return spr_SMB_shell_empty_night;
	            else
	                return spr_SMB_shell_empty;
	        case -70:
	            return spr_SMB_shell_empty_spiny;
	        case -73:
	            return spr_SMB_podoboo;
	        case -72:
	            return spr_SMB_sledgebro;
	        case -71:
	            return spr_SMB_pplant_fire_down;
	        case -74:
	            return spr_SMB_goomba_shoe;
	        case -75:
	            return spr_SMB_goomba_shoe_red;
	        case -106:
	            return spr_SMB_waddlewing;
	        default:
	            return -1;
	    }
    
	}
	else if (global.apariencia == 1)
	{
	    switch argument0
	    {
	        case 1:
	            return spr_SMB3_mushroom;
	        case 2:
	            return spr_SMB3_fireflower;
	        case -50:
	            return spr_SMB3_fireflower;
	        case 3:
	            return spr_cap;
	        case -85:
	            return spr_frogsuit;
	        case -82:
	            return spr_frogsuit;
	        case -43:
	            return spr_frogsuit;
	        case -80:
	            return spr_SMB3_mushroom;
	        case -46:
	            return spr_SMB3_hammersuit;
	        case -30:
	            return spr_leaf;
	        case -38:
	            return spr_SMB3_hammersuit;
	        case -39:
	            return spr_leaf;
	        case -77:
	            return spr_leaf;
	        case -78:
	            return spr_SMB3_mushroom;
	        case -81:
	            return spr_SMB3_shell_drybones;
	        case -18:
	            if (global.bg_level == "ground" && global.modo_noche == 1)
	                return spr_rotten_b;
	            else
	                return spr_SMB3_1up;
	        case -29:
	            return spr_frogsuit;
	        case -21:
	            return spr_SMB3_star;
	        case -22:
	            return spr_SMB3_key;
	        case -1:
	            return spr_SMB3_coin;
	        case -76:
	            return spr_SMB3_pink_coin;
	        case -23:
	            return spr_SMB3_spring;
	        case -25:
	            return spr_SMB3_pswitch;
	        case -28:
	            return spr_SMB3_beanstalk;
	        case -31:
	            return spr_SMB3_koopa
	        case -90:
	            return spr_SMB3_koopa_b;
	        case -32:
	            return spr_SMB3_koopa_red;
	        case -91:
	            return spr_SMB3_koopa_red_b;
	        case -33:
	            return spr_SMB3_spiny;
	        case -34:
	            return spr_SMB3_buzzybeetle;
	        case -54:
	            return spr_SMB3_cheepcheep;
	        case -79:
	            return spr_SMB3_cheepcheep2;
	        case -55:
	            return spr_SMB3_goomba;
	        case -56:
	            return spr_SMB3_goomba2;
	        case -57:
	            return spr_SMB3_bobomb;
	        case -58:
	            return spr_SMB3_bobomb_ready;
	        case -59:
	            return spr_SMB3_hammerbro;
	        case -60:
	            return spr_SMB3_boo;
	        case -61:
	            return spr_SMB3_muncher;
	        case -62:
	            return spr_SMB3_montymole;
	        case -63:
	            return spr_SMB3_pplant;
	        case -64:
	            return spr_SMB3_drybones;
	        case -65:
	            return spr_SMB3_pow;
	        case -66:
	            return spr_SMB3_spring_land;
	        case -67:
	            return spr_SMB3_clown;
	        case -68:
	            return spr_SMB3_clown_fire;
	        case -69:
	            if (global.bg_level == "castle" || global.bg_level == "ghost" || global.bg_level == "underground" || global.modo_noche == 1)
	                return spr_SMB3_shell_empty_night;
	            else
	                return spr_SMB3_shell_empty;
	        case -70:
	            return spr_SMB3_shell_spiny_empty;
	        case -73:
	            return spr_SMB3_podoboo;
	        case -72:
	            return spr_SMB3_sledgebro;
	        case -71:
	            return spr_SMB3_pplant_fire_down;
	        case -74:
	            return spr_SMB3_goomba_shoe;
	        case -75:
	            return spr_SMB3_goomba_shoe_red;
	        case -106:
	            return spr_SMB3_waddlewing;
	        default:
	            return -1;
	    }

	}
	else if (global.apariencia == 2)
	{
	    switch argument0
	    {
	        case 1:
	            return spr_mushroom;
	        case 2:
	            return spr_fireflower;
	        case -50:
	            return spr_fireflower;
	        case -80:
	            return spr_mushroom;
	        case -85:
	            return spr_pballon;
	        case -46:
	            return spr_pballon;
	        case -38:
	            return spr_pballon;
	        case -30:
	            return spr_cap;
	        case -43:
	            return spr_pballon;
	        case 3:
	            return spr_cap;
	        case -82:
	            return spr_pballon;
	        case -39:
	            return spr_leaf;
	        case -77:
	            return spr_cap;
	        case -78:
	            return spr_pballon;
	        case -29:
	            return spr_pballon;
	        case -81:
	            return spr_shell_drybones;
	        case -18:
	            if (global.bg_level == "ground" && global.modo_noche == 1)
	                return spr_rotten_b;
	            else
	                return spr_1up;
	        case -21:
	            return spr_star;
	        case -22:
	            return spr_key;
	        case -1:
	            return spr_coin;
	        case -76:
	            return spr_pink_coin;
	        case -23:
	            return spr_spring;
	        case -25:
	            return spr_pswitch;
	        case -28:
	            return spr_beanstalk;
	        case -31:
	            return spr_koopa;
	        case -90:
	            return spr_koopa_b;
	        case -32:
	            return spr_koopa_red;
	        case -91:
	            return spr_koopa_red_b;
	        case -33:
	            return spr_spiny;
	        case -34:
	            return spr_buzzybeetle;
	        case -54:
	            return spr_cheepcheep;
	        case -79:
	            return spr_cheepcheep2;
	        case -55:
	            return spr_galoomba;
	        case -56:
	            return spr_galoomba2;
	        case -57:
	            return spr_bobomb;
	        case -58:
	            return spr_bobomb_ready;
	        case -59:
	            return spr_hammerbro;
	        case -60:
	            return spr_boo;
	        case -61:
	            return spr_muncher;
	        case -62:
	            return spr_montymole;
	        case -63:
	            return spr_jumppiranha;
	        case -64:
	            return spr_drybones;
	        case -65:
	            return spr_block_pow;
	        case -66:
	            return spr_spring_land;
	        case -67:
	            return spr_clown;
	        case -68:
	            return spr_clown_fire;
	        case -69:
	            return spr_shell_buzzy_empty;
	        case -70:
	            return spr_shell_spiny_empty;
	        case -73:
	            return spr_podoboo;
	        case -72:
	            return spr_sledgebro;
	        case -71:
	            return spr_pplant_fire_down;
	        case -74:
	            return spr_egg;
	        case -75:
	            return spr_egg_red;
	        case -106:
	            return spr_waddlewing;
	        default:
	            return -1;
	    }
    
	}
	else if (global.apariencia == 3)
	{
	    switch argument0
	    {
	        case 1:
	            return spr_NSMBU_mushroom;
	        case 2:
	            return spr_NSMBU_fireflower;
	        case -50:
	            return spr_NSMBU_fireflower;
	        case -80:
	            return spr_NSMBU_superacorn;
	        case -85:
	            return spr_NSMBU_superacorn;
	        case -38:
	            return spr_NSMBU_penguin;
	        case -46:
	            return spr_NSMBU_penguin;
	        case 3:
	            return spr_cap;
	        case -82:
	            return spr_NSMBU_penguin;
	        case -43:
	            return spr_NSMBU_superacorn;
	        case -39:
	            return spr_leaf;
	        case -77:
	            return spr_NSMBU_champicoptero;
	        case -30:
	            return spr_NSMBU_champicoptero;
	        case -78:
	            return spr_NSMBU_superacorn;
	        case -29:
	            return spr_NSMBU_superacorn;
	        case -81:
	            return spr_NSMBU_shell_drybones;
	        case -18:
	            if (global.bg_level == "ground" && global.modo_noche == 1)
	                return spr_rotten_b;
	            else
	                return spr_NSMBU_1up;
	        case -21:
	            return spr_NSMBU_star;
	        case -22:
	            return spr_NSMBU_key;
	        case -1:
	            return spr_NSMBU_coin;
	        case -76:
	            return spr_NSMBU_pink_coin;
	        case -23:
	            return spr_NSMBU_spring;
	        case -25:
	            return spr_NSMBU_pswitch;
	        case -28:
	            return spr_NSMBU_beanstalk;
	        case -31:
	            return spr_NSMBU_koopa;
	        case -90:
	            return spr_NSMBU_koopa_b;
	        case -32:
	            return spr_NSMBU_koopa_red;
	        case -91:
	            return spr_NSMBU_koopa_red_b;
	        case -33:
	            return spr_NSMBU_spiny;
	        case -34:
	            return spr_NSMBU_buzzybeetle;
	        case -54:
	            return spr_NSMBU_cheepcheep;
	        case -79:
	            return spr_NSMBU_cheepcheep2;
	        case -55:
	            return spr_NSMBU_goomba;
	        case -56:
	            return spr_NSMBU_goombrat;
	        case -57:
	            return spr_NSMBU_bobomb;
	        case -58:
	            return spr_NSMBU_bobomb_ready;
	        case -59:
	            return spr_NSMBU_hammerbro;
	        case -60:
	            return spr_NSMBU_boo_overworld;
	        case -61:
	            return spr_NSMBU_muncher;
	        case -62:
	            return spr_NSMBU_montymole;
	        case -63:
	            return spr_NSMBU_pplant;
	        case -64:
	            return spr_NSMBU_drybones;
	        case -65:
	            return spr_NSMBU_pow;
	        case -66:
	            return spr_NSMBU_spring_land;
	        case -67:
	            return spr_NSMBU_clown;
	        case -68:
	            return spr_NSMBU_clown_fire;
	        case -69:
	            return spr_NSMBU_shell_buzzy_empty;
	        case -70:
	            return spr_NSMBU_shell_spiny_empty;
	        case -73:
	            return spr_NSMBU_podoboo;
	        case -72:
	            return spr_NSMBU_sledgebro;
	        case -71:
	            return spr_NSMBU_pplant_fire_down;
	        case -74:
	            return spr_NSMBU_egg;
	        case -75:
	            return spr_NSMBU_egg_red;
	        case -106:
	            return spr_NSMBU_waddlewing;
	        default:
	            return -1;
	    }
    
	}
	else if (global.apariencia == 4)
	{
	    switch argument0
	    {
	        case 1:
	            return spr_SMB2_mushroom;
	        case 2:
	            return spr_SMB_fireflower;
	        case -50:
	            return spr_SMB_superflower;
	        case -80:
	            return spr_SMB2_mushroom;
	        case -77:
	            return spr_SMB_megamushroom;
	        case -85:
	            return spr_SMB_link;
	        case -78:
	            return spr_SMB_hen_mushroom;
	        case -30:
	            return spr_SMB_megamushroom;
	        case -46:
	            return spr_SMB_hen_mushroom;
	        case -43:
	            return spr_SMB_hen_mushroom;
	        case 3:
	            return spr_SMB_megamushroom;
	        case -82:
	            return spr_SMB_hen_mushroom;
	        case -39:
	            return spr_SMB_megamushroom;
	        case -29:
	            return spr_SMB_hen_mushroom;
	        case -38:
	            return spr_SMB_hen_mushroom;
	        case -81:
	            return spr_SMB_shell_drybones;
	        case -18:
	            if (global.bg_level == "ground" && global.modo_noche == 1)
	                return spr_rotten_b;
	            else
	                return spr_SMB_1up;
	        case -21:
	            return spr_SMB_star;
	        case -22:
	            return spr_SMB_key;
	        case -1:
	            return spr_SMB_coin;
	        case -76:
	            return spr_SMB_pink_coin;
	        case -23:
	            return spr_SMB_spring;
	        case -25:
	            return spr_SMB_pswitch;
	        case -28:
	            return spr_SMB_beanstalk;
	        case -31:
	            return spr_SMB_koopa;
	        case -32:
	            return spr_SMB_koopa_red;
	        case -33:
	            return spr_SMB_spiny;
	        case -34:
	            return spr_SMB_buzzybeetle;
	        case -54:
	            return spr_SMB_cheepcheep;
	        case -79:
	            return spr_SMB_cheepcheep2;
	        case -55:
	            return spr_SMB_goomba;
	        case -56:
	            return spr_SMB_goomba2;
	        case -57:
	            return spr_SMB_bobomb;
	        case -58:
	            return spr_SMB_bobomb_ready;
	        case -59:
	            return spr_SMB_hammerbro;
	        case -60:
	            return spr_SMB_boo;
	        case -61:
	            return spr_SMB_muncher;
	        case -62:
	            return spr_SMB_montymole;
	        case -63:
	            return spr_SMB_pplant;
	        case -64:
	            return spr_SMB_drybones;
	        case -65:
	            return spr_SMB_pow;
	        case -66:
	            return spr_SMB_spring_land;
	        case -67:
	            return spr_SMB_clown;
	        case -68:
	            return spr_SMB_clown_fire;
	        case -69:
	            if (global.bg_level == "castle" || global.bg_level == "ghost" || global.bg_level == "underground" || global.modo_noche == 1)
	                return spr_SMB_shell_empty_night;
	            else
	                return spr_SMB_shell_empty;
	        case -70:
	            return spr_SMB_shell_empty_spiny;
	        case -73:
	            return spr_SMB_podoboo;
	        case -72:
	            return spr_SMB_sledgebro;
	        case -71:
	            return spr_SMB_pplant_fire_down;
	        case -74:
	            return spr_SMB_goomba_shoe;
	        case -75:
	            return spr_SMB_goomba_shoe_red;
	        default:
	            return -1;
	    }
    
	}


}
