audio_stop_sound(snd_circle_1)
audio_stop_sound(snd_circle_2)
audio_stop_sound(snd_circle_3)
audio_stop_sound(snd_circle_4)
audio_stop_sound(snd_circle_5)
audio_stop_sound(snd_circle_6)
audio_stop_sound(snd_circle_7)
audio_stop_sound(snd_circle_8)
if (value == 0)
    audio_play_sound(snd_circle_1, 0, false)
else if (value == 1)
    audio_play_sound(snd_circle_2, 0, false)
else if (value == 2)
    audio_play_sound(snd_circle_3, 0, false)
else if (value == 3)
    audio_play_sound(snd_circle_4, 0, false)
else if (value == 4)
    audio_play_sound(snd_circle_5, 0, false)
else if (value == 5)
    audio_play_sound(snd_circle_6, 0, false)
else if (value == 6)
    audio_play_sound(snd_circle_7, 0, false)
else if (value == 7 || value == 8 || value == 9)
    audio_play_sound(snd_circle_8, 0, false)

