draw_sprite(spr_letters_super, 1, (camera_get_view_x(view_get_camera(0)) + 96), (camera_get_view_y(view_get_camera(0)) + 36))
draw_sprite(spr_letters_white, 0, (camera_get_view_x(view_get_camera(0)) + 96), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 1, (camera_get_view_x(view_get_camera(0)) + 119), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 2, (camera_get_view_x(view_get_camera(0)) + 138), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 3, (camera_get_view_x(view_get_camera(0)) + 157), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 4, (camera_get_view_x(view_get_camera(0)) + 165), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 4, (camera_get_view_x(view_get_camera(0)) + 165), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 0, (camera_get_view_x(view_get_camera(0)) + 195), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 1, (camera_get_view_x(view_get_camera(0)) + 218), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 5, (camera_get_view_x(view_get_camera(0)) + 237), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 6, (camera_get_view_x(view_get_camera(0)) + 256), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_letters_white, 2, (camera_get_view_x(view_get_camera(0)) + 273), (camera_get_view_y(view_get_camera(0)) + 57))
draw_sprite(spr_we, 1, (camera_get_view_y(view_get_camera(0)) + 214), (camera_get_view_y(view_get_camera(0)) + 90))

