function scr_sprite_get_constant_res(argument0) //gml_Script_scr_sprite_get_constant_res
{
    if (global.apariencia == 0)
    {
        switch argument0
        {
            case spr_SMB_mushroom:
                return 1;
            case spr_SMB_fireflower_res:
                return 2;
            case spr_SMB_superflower_res:
                return -50;
            case spr_SMB_megamushroom_res:
                return -77;
            case spr_SMB_link_res:
                return -85;
            case spr_frogsuit:
                return -78;
            case spr_SMB_hen_mushroom:
                return -78;
            case spr_koopa_res:
                return -31;
            case spr_koopa_b_res:
                return -90;
            case spr_koopa_red_res:
                return -32;
            case spr_koopa_red_b_res:
                return -91;
            case spr_shell_drybones_res:
                return -81;
            case spr_SMB_1up:
                return -18;
            case spr_rotten_b:
                return -18;
            case spr_star_res:
                return -21;
            case spr_SMB_coin:
                return -1;
            case spr_SMB_key:
                return -22;
            case spr_SMB3_pink_coin:
                return -76;
            case spr_SMB_spring:
                return -23;
            case spr_SMB_pswitch:
                return -25;
            case spr_SMB_vine_green:
                return -28;
            case spr_spiny_res:
                return -33;
            case spr_spiny_wings_res:
                return -33;
            case spr_SMB_buzzybeetle_res:
                return -34;
            case spr_SMB_buzzybeetle_night_res:
                return -34;
            case spr_SMB_buzzy_wings_res:
                return -34;
            case spr_cheepcheep_res:
                return -54;
            case spr_cheepcheep2_res:
                return -79;
            case spr_goomba_res:
                return -55;
            case spr_goombrat_res:
                return -56;
            case spr_bobomb_res:
                return -57;
            case spr_bobomb_ready_res:
                return -58;
            case spr_hammerbro_res:
                return -59;
            case spr_SMB_boo_res:
                return -60;
            case spr_muncher_res:
                return -61;
            case spr_muncher_night_res:
                return -61;
            case spr_monty_res:
                return -62;
            case spr_pplant_res:
                return -63;
            case spr_drybones_res:
                return -64;
            case spr_SMB_pow:
                return -65;
            case spr_spring_land_res:
                return -66;
            case spr_SMB_clown:
                return -67;
            case spr_SMB_clown_fire:
                return -68;
            case spr_shell_empty_res:
                return -69;
            case spr_spiny_shell_res:
                return -70;
            case spr_podoboo_res:
                return -73;
            case spr_SMB3_sledgebro:
                return -72;
            case spr_plant_fire_res:
                return -71;
            case spr_SMB_shoe_res:
                return -74;
            case spr_SMB_shoe_red_res:
                return -75;
            case spr_chainchomp_res:
                return -83;
            case spr_SMB_waddlewing:
                return -106;
            default:
                return -1;
        }

    }
    else if (global.apariencia == 1)
    {
        switch argument0
        {
            case spr_SMB3_mushroom:
                return 1;
            case spr_SMB3_fireflower_res:
                return 2;
            case spr_SMB_superflower_res:
                return 2;
            case spr_cap_res:
                return 3;
            case spr_SMB_megamushroom_res:
                return 3;
            case spr_frogsuit:
                return -29;
            case spr_SMB3_hammersuit_res:
                return -46;
            case spr_SMB_hen_mushroom:
                return 1;
            case spr_SMB3_leaf_res:
                return -39;
            case spr_koopa_res:
                return -31;
            case spr_koopa_b_res:
                return -90;
            case spr_koopa_red_res:
                return -32;
            case spr_koopa_red_b_res:
                return -91;
            case spr_shell_drybones_res:
                return -81;
            case spr_SMB3_1up:
                return -18;
            case spr_rotten_b:
                return -18;
            case spr_star_res:
                return -21;
            case spr_SMB3_coin:
                return -1;
            case spr_SMB3_key:
                return -22;
            case spr_SMB3_pink_coin:
                return -76;
            case spr_SMB3_spring:
                return -23;
            case spr_SMB3_pswitch:
                return -25;
            case spr_SMB3_vine_green:
                return -28;
            case spr_spiny_res:
                return -33;
            case spr_spiny_wings_res:
                return -33;
            case spr_SMB3_buzzybeetle_res:
                return -34;
            case spr_SMB3_buzzybeetle_night_res:
                return -34;
            case spr_SMB3_buzzy_wings_res:
                return -34;
            case spr_cheepcheep_res:
                return -54;
            case spr_cheepcheep2_res:
                return -79;
            case spr_goomba_res:
                return -55;
            case spr_goombrat_res:
                return -56;
            case spr_bobomb_res:
                return -57;
            case spr_bobomb_ready_res:
                return -58;
            case spr_hammerbro_res:
                return -59;
            case spr_SMB3_boo_res:
                return -60;
            case spr_muncher_res:
                return -61;
            case spr_muncher_night_res:
                return -61;
            case spr_monty_res:
                return -62;
            case spr_pplant_res:
                return -63;
            case spr_SMB3_drybones:
                return -64;
            case spr_SMB3_pow:
                return -65;
            case spr_spring_land_res:
                return -66;
            case spr_SMB3_clown:
                return -67;
            case spr_SMB3_clown_fire:
                return -68;
            case spr_shell_empty_res:
                return -69;
            case spr_spiny_shell_res:
                return -70;
            case spr_podoboo_res:
                return -73;
            case spr_SMB3_sledgebro:
                return -72;
            case spr_plant_fire_res:
                return -71;
            case spr_shoe_res:
                return -74;
            case spr_shoe_red_res:
                return -75;
            case spr_chainchomp_res:
                return -83;
            case spr_SMB3_waddlewing:
                return -106;
            default:
                return -1;
        }

    }
    else if (global.apariencia == 2)
    {
        switch argument0
        {
            case spr_mushroom:
                return 1;
            case spr_fireflower_res:
                return 2;
            case spr_SMB_superflower_res:
                return 2;
            case spr_cap_res:
                return 3;
            case spr_SMB_megamushroom_res:
                return 3;
            case spr_SMB_hen_mushroom:
                return 1;
            case spr_pballon_res:
                return -82;
            case spr_SMB3_leaf_res:
                return 3;
            case spr_koopa_res:
                return -31;
            case spr_koopa_b_res:
                return -90;
            case spr_koopa_red_res:
                return -32;
            case spr_koopa_red_b_res:
                return -91;
            case spr_shell_drybones_res:
                return -81;
            case spr_1up:
                return -18;
            case spr_rotten_b:
                return -18;
            case spr_star_res:
                return -21;
            case spr_coin:
                return -1;
            case spr_key:
                return -22;
            case spr_pink_coin:
                return -76;
            case spr_spring:
                return -23;
            case spr_pswitch:
                return -25;
            case spr_vine_green:
                return -28;
            case spr_spiny_res:
                return -33;
            case spr_spiny_wings_res:
                return -33;
            case spr_buzzybeetle_res:
                return -34;
            case spr_buzzy_wings_res:
                return -34;
            case spr_cheepcheep_res:
                return -54;
            case spr_cheepcheep2_res:
                return -79;
            case spr_goomba_res:
                return -55;
            case spr_goombrat_res:
                return -56;
            case spr_bobomb_res:
                return -57;
            case spr_bobomb_ready_res:
                return -58;
            case spr_hammerbro_res:
                return -59;
            case spr_boo_res:
                return -60;
            case spr_muncher_res:
                return -61;
            case spr_muncher_night_res:
                return -61;
            case spr_monty_res:
                return -62;
            case spr_pplant_res:
                return -63;
            case spr_drybones_res:
                return -64;
            case spr_block_pow:
                return -65;
            case spr_spring_land_res:
                return -66;
            case spr_clown:
                return -67;
            case spr_clown_fire:
                return -68;
            case spr_shell_empty_res:
                return -69;
            case spr_spiny_shell_res:
                return -70;
            case spr_podoboo_res:
                return -73;
            case spr_sledgebro:
                return -72;
            case spr_plant_fire_res:
                return -71;
            case spr_egg:
                return -74;
            case spr_egg_red:
                return -75;
            case spr_chainchomp_res:
                return -83;
            case spr_waddlewing:
                return -106;
            default:
                return -1;
        }

    }
    else if (global.apariencia == 3)
    {
        switch argument0
        {
            case spr_NSMBU_mushroom:
                return 1;
            case spr_NSMBU_fireflower_res:
                return 2;
            case spr_SMB_superflower_res:
                return 2;
            case spr_cap_res:
                return 3;
            case spr_NSMBU_penguin_suit_res:
                return -38;
            case spr_NSMBU_champicoptero_res:
                return -30;
            case spr_NSMBU_superacorn_res:
                return -43;
            case spr_SMB_megamushroom_res:
                return 3;
            case spr_SMB_hen_mushroom:
                return 1;
            case spr_SMB3_leaf_res:
                return 3;
            case spr_koopa_res:
                return -31;
            case spr_koopa_b_res:
                return -90;
            case spr_koopa_red_b_res:
                return -91;
            case spr_shell_drybones_res:
                return -81;
            case spr_koopa_red_res:
                return -32;
            case spr_NSMBU_1up:
                return -18;
            case spr_rotten_b:
                return -18;
            case spr_star_res:
                return -21;
            case spr_NSMBU_coin:
                return -1;
            case spr_NSMBU_key:
                return -22;
            case spr_pink_coin:
                return -76;
            case spr_NSMBU_spring:
                return -23;
            case spr_NSMBU_pswitch:
                return -25;
            case spr_NSMBU_vine_green:
                return -28;
            case spr_spiny_res:
                return -33;
            case spr_spiny_wings_res:
                return -33;
            case spr_NSMBU_buzzybeetle_res:
                return -34;
            case spr_cheepcheep_res:
                return -54;
            case spr_cheepcheep2_res:
                return -79;
            case spr_goomba_res:
                return -55;
            case spr_goombrat_res:
                return -56;
            case spr_bobomb_res:
                return -57;
            case spr_bobomb_ready_res:
                return -58;
            case spr_hammerbro_res:
                return -59;
            case spr_NSMBU_boo_overworld_res:
                return -60;
            case spr_NSMBU_boo_ghost_res:
                return -60;
            case spr_muncher_res:
                return -61;
            case spr_muncher_night_res:
                return -61;
            case spr_monty_res:
                return -62;
            case spr_pplant_res:
                return -63;
            case spr_drybones_res:
                return -64;
            case spr_NSMBU_pow:
                return -65;
            case spr_spring_land_res:
                return -66;
            case spr_NSMBU_clown:
                return -67;
            case spr_NSMBU_clown_fire:
                return -68;
            case spr_shell_empty_res:
                return -69;
            case spr_spiny_shell_res:
                return -70;
            case spr_podoboo_res:
                return -73;
            case spr_sledgebro_res:
                return -72;
            case spr_plant_fire_res:
                return -71;
            case spr_NSMBU_egg:
                return -74;
            case spr_NSMBU_egg_red:
                return -75;
            case spr_chainchomp_res:
                return -83;
            case spr_NSMBU_waddlewing_res:
                return -106;
            default:
                return -1;
        }
	}
	else if (global.apariencia == 4)
	{
		switch argument0
        {
            case spr_SMB_mushroom:
                return 1;
            case spr_SMB_fireflower_res:
                return 2;
            case spr_SMB_superflower_res:
                return -50;
            case spr_SMB_megamushroom_res:
                return -77;
            case spr_SMB_link_res:
                return -85;
            case spr_frogsuit:
                return -78;
            case spr_SMB_hen_mushroom:
                return -78;
            case spr_koopa_res:
                return -31;
            case spr_koopa_b_res:
                return -90;
            case spr_koopa_red_res:
                return -32;
            case spr_shell_drybones_res:
                return -81;
            case spr_SMB_1up:
                return -18;
            case spr_rotten_b:
                return -18;
            case spr_star_res:
                return -21;
            case spr_SMB_coin:
                return -1;
            case spr_SMB_key:
                return -22;
            case spr_SMB3_pink_coin:
                return -76;
            case spr_SMB_spring:
                return -23;
            case spr_SMB_pswitch:
                return -25;
            case spr_SMB_vine_green:
                return -28;
            case spr_spiny_res:
                return -33;
            case spr_spiny_wings_res:
                return -33;
            case spr_SMB_buzzybeetle_res:
                return -34;
            case spr_SMB_buzzybeetle_night_res:
                return -34;
            case spr_SMB_buzzy_wings_res:
                return -34;
            case spr_cheepcheep_res:
                return -54;
            case spr_cheepcheep2_res:
                return -79;
            case spr_goomba_res:
                return -55;
            case spr_goombrat_res:
                return -56;
            case spr_bobomb_res:
                return -57;
            case spr_bobomb_ready_res:
                return -58;
            case spr_hammerbro_res:
                return -59;
            case spr_SMB_boo_res:
                return -60;
            case spr_muncher_res:
                return -61;
            case spr_muncher_night_res:
                return -61;
            case spr_monty_res:
                return -62;
            case spr_pplant_res:
                return -63;
            case spr_drybones_res:
                return -64;
            case spr_SMB_pow:
                return -65;
            case spr_spring_land_res:
                return -66;
            case spr_SMB_clown:
                return -67;
            case spr_SMB_clown_fire:
                return -68;
            case spr_shell_empty_res:
                return -69;
            case spr_spiny_shell_res:
                return -70;
            case spr_podoboo_res:
                return -73;
            case spr_SMB3_sledgebro:
                return -72;
            case spr_plant_fire_res:
                return -71;
            case spr_SMB_shoe_res:
                return -74;
            case spr_SMB_shoe_red_res:
                return -75;
            case spr_chainchomp_res:
                return -83;
            default:
                return -1;
        }

}
}
