with (obj_logo_game)
    instance_destroy()
with (obj_panel_time)
    instance_destroy()
with (obj_card_bg)
    instance_destroy()
with (obj_card_bout)
    instance_destroy()
with (obj_button_sdog)
    instance_destroy()

