image_speed = 0
image_index = 0
c_etiqueta = make_colour_rgb(89, 15, 16)
index = 0
idd = 0
selected = 0
disabled = 0
effect_hover = 0
anim = 0
text_draw[0] = scr_language(52);
text_draw[1] = scr_language(53);
text_draw[2] = scr_language(54);
text_draw[3] = scr_language(55);
text_draw[4] = scr_language(56);
text_draw[5] = scr_language(57);
text_draw[6] = scr_language(58);
text_draw[7] = scr_language(59);
text_draw[8] = scr_language(60);
text_draw[9] = scr_language(61);
text_draw[10] = scr_language(62);
text_draw[11] = scr_language(63);
text_draw[12] = scr_language(64);
text_draw[13] = scr_language(65);
text_draw[14] = "Link";
text[0] = "Tradicional"
text[1] = "Puzles"
text[2] = "Contrarreloj"
text[3] = "Autoavance"
text[4] = "Automatismos"
text[5] = "Corto pero intenso"
text[6] = "Competitivo"
text[7] = "Tematico"
text[8] = "Música"
text[9] = "Artístico"
text[10] = "Habilidad"
text[11] = "Disparos"
text[12] = "Contra jefes"
text[13] = "En solitario"
text[14] = "Link"