function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -9; // obj_lighting
	global.__objectDepths[1] = -20; // obj_rainmaker
	global.__objectDepths[2] = -7; // obj_snowmaker
	global.__objectDepths[3] = -7; // obj_leafmaker
	global.__objectDepths[4] = -7; // obj_firemaker
	global.__objectDepths[5] = 12; // obj_flagpole
	global.__objectDepths[6] = 11; // obj_SMB_flag
	global.__objectDepths[7] = 10; // obj_NSMBU_flag_mario
	global.__objectDepths[8] = -6; // obj_score_flag
	global.__objectDepths[9] = 10; // obj_SMB_castle
	global.__objectDepths[10] = 10; // obj_SMB_castle_front
	global.__objectDepths[11] = 11; // obj_mini_flag
	global.__objectDepths[12] = 301; // obj_goalcard
	global.__objectDepths[13] = -5; // obj_goalcard_get
	global.__objectDepths[14] = 9; // obj_goalgate
	global.__objectDepths[15] = -11; // obj_goalgate_front
	global.__objectDepths[16] = 8; // obj_goalgate_tape
	global.__objectDepths[17] = -8; // obj_mario
	global.__objectDepths[18] = -8; // obj_marioU
	global.__objectDepths[19] = 8; // obj_checkpoint
	global.__objectDepths[20] = -11; // obj_levelmanager
	global.__objectDepths[21] = 0; // obj_autoscroll
	global.__objectDepths[22] = 0; // obj_bganimator
	global.__objectDepths[23] = -14; // obj_shake_mario
	global.__objectDepths[24] = -8; // obj_platform_help
	global.__objectDepths[25] = 0; // obj_fallow_view
	global.__objectDepths[26] = -7; // obj_koopa_b
	global.__objectDepths[27] = -7; // obj_koopa_red_b
	global.__objectDepths[28] = 0; // obj_beachkoopa_b
	global.__objectDepths[29] = 0; // obj_beachkoopa_red_b
	global.__objectDepths[30] = 0; // obj_galoomba
	global.__objectDepths[31] = 0; // obj_galoomba2
	global.__objectDepths[32] = -7; // obj_koopa
	global.__objectDepths[33] = -7; // obj_koopa_red
	global.__objectDepths[34] = 0; // obj_beachkoopa
	global.__objectDepths[35] = 0; // obj_beachkoopa_red
	global.__objectDepths[36] = -2; // obj_floruga
	global.__objectDepths[37] = 0; // obj_floruga_body
	global.__objectDepths[38] = 0; // obj_goomba_swim
	global.__objectDepths[39] = 0; // obj_buzzybeetle
	global.__objectDepths[40] = 0; // obj_buzzybeetle_b
	global.__objectDepths[41] = 0; // obj_spiny
	global.__objectDepths[42] = 0; // obj_spiny_ball
	global.__objectDepths[43] = 0; // obj_buzzy_ceiling
	global.__objectDepths[44] = -6; // obj_jumppiranha
	global.__objectDepths[45] = 12; // obj_piranhaplant
	global.__objectDepths[46] = 0; // obj_plant_fire
	global.__objectDepths[47] = -7; // obj_cheepcheep
	global.__objectDepths[48] = -7; // obj_cheepcheep2
	global.__objectDepths[49] = -7; // obj_blooper
	global.__objectDepths[50] = -7; // obj_angrysun
	global.__objectDepths[51] = -2; // obj_monty_chase
	global.__objectDepths[52] = -2; // obj_spike
	global.__objectDepths[53] = -3; // obj_spike_ball
	global.__objectDepths[54] = 0; // obj_snow_ball
	global.__objectDepths[55] = -1; // obj_snow_ball_held
	global.__objectDepths[56] = -2; // obj_pokey
	global.__objectDepths[57] = -1; // obj_lakitu
	global.__objectDepths[58] = -3; // obj_spiny_thrown
	global.__objectDepths[59] = 2; // obj_cloud_lakitu
	global.__objectDepths[60] = -2; // obj_boo
	global.__objectDepths[61] = 0; // obj_drybones
	global.__objectDepths[62] = 0; // obj_bonybeetle
	global.__objectDepths[63] = 0; // obj_bonybeetle_b
	global.__objectDepths[64] = -2; // obj_thwomp
	global.__objectDepths[65] = -2; // obj_grrrol
	global.__objectDepths[66] = -7; // obj_podoboo
	global.__objectDepths[67] = -7; // obj_podoboo_b
	global.__objectDepths[68] = -7; // obj_grinder
	global.__objectDepths[69] = -2; // obj_magikoopa
	global.__objectDepths[70] = -7; // obj_firebar
	global.__objectDepths[71] = 0; // obj_bobomb
	global.__objectDepths[72] = 0; // obj_bobomb_ready
	global.__objectDepths[73] = -2; // obj_bullebill_base
	global.__objectDepths[74] = -2; // obj_bullebill_base_red
	global.__objectDepths[75] = 10; // obj_bulletbill
	global.__objectDepths[76] = 10; // obj_bulletbull_red
	global.__objectDepths[77] = -8; // obj_banzaibill
	global.__objectDepths[78] = -8; // obj_billbanzai_red
	global.__objectDepths[79] = -3; // obj_cannon
	global.__objectDepths[80] = -3; // obj_cannon_red
	global.__objectDepths[81] = -2; // obj_soplete
	global.__objectDepths[82] = -2; // obj_soplete_invert
	global.__objectDepths[83] = 0; // obj_soplete_global
	global.__objectDepths[84] = 0; // obj_soplete_invert_global
	global.__objectDepths[85] = -7; // obj_chain_chomp_free
	global.__objectDepths[86] = -2; // obj_foo
	global.__objectDepths[87] = -11; // obj_foo_fog
	global.__objectDepths[88] = 0; // obj_mechakoopa
	global.__objectDepths[89] = -2; // obj_mechakoopa_held
	global.__objectDepths[90] = -2; // obj_rocky
	global.__objectDepths[91] = 0; // obj_rocangrejo
	global.__objectDepths[92] = -1; // obj_SMB_bowser
	global.__objectDepths[93] = -1; // obj_SMB3_bowser
	global.__objectDepths[94] = -1; // obj_SMW_bowser
	global.__objectDepths[95] = -1; // obj_NSMBU_bowser
	global.__objectDepths[96] = -1; // obj_bowserjr
	global.__objectDepths[97] = -1; // obj_NSMBU_bowserjr
	global.__objectDepths[98] = -2; // obj_bowserjr_shell
	global.__objectDepths[99] = -2; // obj_boomboom
	global.__objectDepths[100] = -2; // obj_NSMBU_boomboom
	global.__objectDepths[101] = -2; // obj_hammerbro
	global.__objectDepths[102] = -2; // obj_sledgebro
	global.__objectDepths[103] = -2; // obj_charginchuck
	global.__objectDepths[104] = -8; // obj_wings_dead
	global.__objectDepths[105] = -8; // obj_wings_dead_b
	global.__objectDepths[106] = -7; // obj_paracaidas_dead
	global.__objectDepths[107] = 5; // obj_paracaidas_go
	global.__objectDepths[108] = -1; // obj_solid
	global.__objectDepths[109] = -1; // obj_solidtop
	global.__objectDepths[110] = 1; // obj_climb
	global.__objectDepths[111] = -1; // obj_solidphy
	global.__objectDepths[112] = 1; // obj_enabledsolid
	global.__objectDepths[113] = -1; // obj_hurtsolid2
	global.__objectDepths[114] = -1; // obj_solidhold
	global.__objectDepths[115] = -1; // obj_solid_appear
	global.__objectDepths[116] = 9; // obj_block
	global.__objectDepths[117] = 9; // obj_block_multicoin
	global.__objectDepths[118] = 1; // obj_block_coinchain
	global.__objectDepths[119] = 9; // obj_block_hidden
	global.__objectDepths[120] = 9; // obj_flipblock
	global.__objectDepths[121] = 9; // obj_flipblock_anim
	global.__objectDepths[122] = 9; // obj_block_gold
	global.__objectDepths[123] = -1; // obj_noteblock
	global.__objectDepths[124] = -7; // obj_musicblock
	global.__objectDepths[125] = -7; // obj_noteblock_s
	global.__objectDepths[126] = 1; // obj_onoffblock
	global.__objectDepths[127] = 1; // obj_onoffplatform
	global.__objectDepths[128] = 1; // obj_onoffplatform_blue
	global.__objectDepths[129] = 9; // obj_block_rock
	global.__objectDepths[130] = 9; // obj_block_ice
	global.__objectDepths[131] = 1; // obj_pblock
	global.__objectDepths[132] = 1; // obj_anti_pblock
	global.__objectDepths[133] = 2; // obj_nube
	global.__objectDepths[134] = 0; // obj_onoffplatform_d
	global.__objectDepths[135] = 9; // obj_pipebase
	global.__objectDepths[136] = 6; // obj_vine_green
	global.__objectDepths[137] = 259; // obj_beanstalk
	global.__objectDepths[138] = 260; // obj_vine
	global.__objectDepths[139] = -1; // obj_muncher
	global.__objectDepths[140] = -1; // obj_muncher_b
	global.__objectDepths[141] = -2; // obj_pinchos
	global.__objectDepths[142] = -5; // obj_mini_icicle
	global.__objectDepths[143] = -5; // obj_mini_icicle2
	global.__objectDepths[144] = -5; // obj_icicle
	global.__objectDepths[145] = -5; // obj_icicle2
	global.__objectDepths[146] = 14; // obj_arrow
	global.__objectDepths[147] = -7; // obj_plataforma
	global.__objectDepths[148] = -7; // obj_plataforma_blue
	global.__objectDepths[149] = -7; // obj_donut
	global.__objectDepths[150] = 5; // obj_fast_lava_lift
	global.__objectDepths[151] = 5; // obj_lava_lift
	global.__objectDepths[152] = 5; // obj_lava_lift_part
	global.__objectDepths[153] = 0; // obj_bouncycloud
	global.__objectDepths[154] = 1; // obj_coin
	global.__objectDepths[155] = 9; // obj_icecoin
	global.__objectDepths[156] = 1; // obj_pink_coin
	global.__objectDepths[157] = 1; // obj_coin10
	global.__objectDepths[158] = 1; // obj_coin30
	global.__objectDepths[159] = 1; // obj_coin50
	global.__objectDepths[160] = 0; // obj_spring
	global.__objectDepths[161] = 0; // obj_spring_land
	global.__objectDepths[162] = 1; // obj_coin_pow
	global.__objectDepths[163] = 1; // obj_coin_pow_big
	global.__objectDepths[164] = -2; // obj_pswitch
	global.__objectDepths[165] = 0; // obj_pswitch_press
	global.__objectDepths[166] = 0; // obj_block_pow_hold
	global.__objectDepths[167] = -7; // obj_block_pow_active
	global.__objectDepths[168] = -6; // obj_quicksand
	global.__objectDepths[169] = -7; // obj_bumper
	global.__objectDepths[170] = 14; // obj_onewaygate_right
	global.__objectDepths[171] = 14; // obj_onewaygate_left
	global.__objectDepths[172] = 14; // obj_onewaygate_top
	global.__objectDepths[173] = 14; // obj_onewaygate_bottom
	global.__objectDepths[174] = 0; // obj_key
	global.__objectDepths[175] = 0; // obj_key_appear
	global.__objectDepths[176] = -7; // obj_key_fallow
	global.__objectDepths[177] = -3; // obj_torbellino
	global.__objectDepths[178] = -7; // obj_bortice
	global.__objectDepths[179] = 5; // obj_door
	global.__objectDepths[180] = 5; // obj_door_exit
	global.__objectDepths[181] = 5; // obj_door_switch
	global.__objectDepths[182] = 5; // obj_door_switch_exit
	global.__objectDepths[183] = 5; // obj_door_lock
	global.__objectDepths[184] = 5; // obj_door_lock_exit
	global.__objectDepths[185] = 11; // obj_tuberia
	global.__objectDepths[186] = 0; // obj_deactivation
	global.__objectDepths[187] = 0; // obj_physicsparent
	global.__objectDepths[188] = 0; // obj_powerupparent
	global.__objectDepths[189] = 0; // obj_enemyparent
	global.__objectDepths[190] = 0; // obj_deactenemyparent
	global.__objectDepths[191] = -2; // obj_bossparent
	global.__objectDepths[192] = 0; // obj_player_goal_parent
	global.__objectDepths[193] = -1; // obj_blockparent
	global.__objectDepths[194] = 9; // obj_rockparent
	global.__objectDepths[195] = 0; // obj_holdparent
	global.__objectDepths[196] = 0; // obj_slopeparent
	global.__objectDepths[197] = -2; // obj_enemyparent_held
	global.__objectDepths[198] = 0; // obj_enemyparent_lava
	global.__objectDepths[199] = -7; // obj_platform_parent
	global.__objectDepths[200] = 0; // obj_physicssolid
	global.__objectDepths[201] = -14; // obj_deadmario
	global.__objectDepths[202] = -8; // obj_mario_temp
	global.__objectDepths[203] = -5; // obj_doormario
	global.__objectDepths[204] = -5; // obj_doormario_exit
	global.__objectDepths[205] = 13; // obj_player_warp
	global.__objectDepths[206] = -8; // obj_mario_pballon
	global.__objectDepths[207] = -5; // obj_player_goal_smb1
	global.__objectDepths[208] = -5; // obj_player_goal_smb3
	global.__objectDepths[209] = -5; // obj_player_goal_smw
	global.__objectDepths[210] = -5; // obj_player_goal_smw_castle
	global.__objectDepths[211] = -5; // obj_player_goal_nsmbu
	global.__objectDepths[212] = 0; // obj_slider
	global.__objectDepths[213] = -8; // obj_spinner
	global.__objectDepths[214] = -6; // obj_mario_transform2
	global.__objectDepths[215] = 0; // obj_penguin_attack
	global.__objectDepths[216] = 0; // obj_groundpount
	global.__objectDepths[217] = -15; // obj_icon_dead
	global.__objectDepths[218] = -2; // obj_1up
	global.__objectDepths[219] = -2; // obj_mushroom
	global.__objectDepths[220] = -2; // obj_fireflower
	global.__objectDepths[221] = 2; // obj_superflower
	global.__objectDepths[222] = -7; // obj_cap
	global.__objectDepths[223] = -2; // obj_megamushroom
	global.__objectDepths[224] = -2; // obj_hen_mushroom
	global.__objectDepths[225] = 0; // obj_pballon
	global.__objectDepths[226] = -2; // obj_star
	global.__objectDepths[227] = 2; // obj_propellershroom
	global.__objectDepths[228] = 2; // obj_frogsuit
	global.__objectDepths[229] = 2; // obj_hammersuit
	global.__objectDepths[230] = 0; // obj_penguin_suit
	global.__objectDepths[231] = 0; // obj_superarcon
	global.__objectDepths[232] = -2; // obj_egg
	global.__objectDepths[233] = 2; // obj_egg_hatch
	global.__objectDepths[234] = -7; // obj_yoshi2
	global.__objectDepths[235] = -4; // obj_yoshi_runaway
	global.__objectDepths[236] = -7; // obj_yoshi_abandon
	global.__objectDepths[237] = -7; // obj_yoshifire
	global.__objectDepths[238] = 0; // obj_yoshifire_purple
	global.__objectDepths[239] = -7; // obj_yoshifire_one
	global.__objectDepths[240] = -7; // obj_tongue
	global.__objectDepths[241] = -2; // obj_egg_red
	global.__objectDepths[242] = -7; // obj_yoshi_red
	global.__objectDepths[243] = -4; // obj_yoshi_runaway_red
	global.__objectDepths[244] = 0; // obj_getshoe
	global.__objectDepths[245] = -9; // obj_kuriboshoe
	global.__objectDepths[246] = -9; // obj_kuriboshoe2
	global.__objectDepths[247] = -7; // obj_smoke_shoe
	global.__objectDepths[248] = 0; // obj_kuriboshoe_movement
	global.__objectDepths[249] = -11; // obj_kuribo_drybones
	global.__objectDepths[250] = -9; // obj_helmet
	global.__objectDepths[251] = -9; // obj_helmet_spiny
	global.__objectDepths[252] = -9; // obj_brickhelmet
	global.__objectDepths[253] = 2; // obj_clown
	global.__objectDepths[254] = 2; // obj_clown_fire
	global.__objectDepths[255] = -12; // obj_fire_clown
	global.__objectDepths[256] = -12; // obj_fire_clown_small
	global.__objectDepths[257] = -7; // obj_clown_explotion
	global.__objectDepths[258] = -4; // obj_cap_mario
	global.__objectDepths[259] = 10; // obj_powerupsprout
	global.__objectDepths[260] = 10; // obj_powerupsprout_note
	global.__objectDepths[261] = -2; // obj_fireball
	global.__objectDepths[262] = 0; // obj_fireball_b
	global.__objectDepths[263] = -2; // obj_snowball
	global.__objectDepths[264] = -2; // obj_superball
	global.__objectDepths[265] = -1; // obj_superball_trail
	global.__objectDepths[266] = -9; // obj_invincibility
	global.__objectDepths[267] = -7; // obj_brohammer_yoshi
	global.__objectDepths[268] = -7; // obj_bones_yoshi
	global.__objectDepths[269] = -7; // obj_bones_yoshi_one
	global.__objectDepths[270] = -9; // obj_hammer
	global.__objectDepths[271] = -9; // obj_hammer_b
	global.__objectDepths[272] = -7; // obj_gold_explosion
	global.__objectDepths[273] = 0; // obj_galoomba_hold
	global.__objectDepths[274] = 0; // obj_galoomba_hold2
	global.__objectDepths[275] = -3; // obj_plantfire
	global.__objectDepths[276] = 0; // obj_espina
	global.__objectDepths[277] = 0; // obj_angrysun_movement
	global.__objectDepths[278] = 0; // obj_crumblebones
	global.__objectDepths[279] = 0; // obj_crumblebony
	global.__objectDepths[280] = 0; // obj_crumblebony_b
	global.__objectDepths[281] = -7; // obj_magic
	global.__objectDepths[282] = -7; // obj_bone
	global.__objectDepths[283] = 0; // obj_bobomb_hold
	global.__objectDepths[284] = -2; // obj_cannonball
	global.__objectDepths[285] = 0; // obj_cannonball_red
	global.__objectDepths[286] = -8; // obj_wrench
	global.__objectDepths[287] = -2; // obj_rorock
	global.__objectDepths[288] = -7; // obj_bowser_fire
	global.__objectDepths[289] = -7; // obj_NSMBU_bowser_fire
	global.__objectDepths[290] = -7; // obj_NSMBU_bowser_fire_up
	global.__objectDepths[291] = -7; // obj_bowserfire_up
	global.__objectDepths[292] = -7; // obj_bowser_fire_down
	global.__objectDepths[293] = -7; // obj_bowserjr_fire
	global.__objectDepths[294] = -7; // obj_NSMBU_bowserjr_fire
	global.__objectDepths[295] = -8; // obj_enemy_dead
	global.__objectDepths[296] = -8; // obj_bowser_dead
	global.__objectDepths[297] = -8; // obj_enemy_dead_castle
	global.__objectDepths[298] = -8; // obj_bowser_dead_castle
	global.__objectDepths[299] = -8; // obj_bowserjr_dead_castle
	global.__objectDepths[300] = 0; // obj_enemy_multidead
	global.__objectDepths[301] = 0; // obj_stomped
	global.__objectDepths[302] = -1; // obj_shell
	global.__objectDepths[303] = -1; // obj_shell_held
	global.__objectDepths[304] = -1; // obj_shell_empty
	global.__objectDepths[305] = -1; // obj_spiny_empty
	global.__objectDepths[306] = -1; // obj_shell_drybones
	global.__objectDepths[307] = -1; // obj_shell_drybones_held
	global.__objectDepths[308] = -7; // obj_brohammer
	global.__objectDepths[309] = 0; // obj_enemyfrozen
	global.__objectDepths[310] = 2; // obj_blockcoin
	global.__objectDepths[311] = 2; // obj_coinchain
	global.__objectDepths[312] = -7; // obj_shard
	global.__objectDepths[313] = -1; // obj_veggiecoin
	global.__objectDepths[314] = -1; // obj_multiveggiecoin
	global.__objectDepths[315] = 0; // obj_coinchange
	global.__objectDepths[316] = 0; // obj_blownbubble
	global.__objectDepths[317] = -30; // obj_curtainin
	global.__objectDepths[318] = -30; // obj_curtainout
	global.__objectDepths[319] = -99; // obj_fadein
	global.__objectDepths[320] = -99; // obj_fadeout
	global.__objectDepths[321] = -2; // obj_score
	global.__objectDepths[322] = -2; // obj_smoke
	global.__objectDepths[323] = -2; // obj_smoke_steps
	global.__objectDepths[324] = -6; // obj_statuesmoke
	global.__objectDepths[325] = -7; // obj_spinsmoke
	global.__objectDepths[326] = -9; // obj_spinthump
	global.__objectDepths[327] = -1; // obj_bubble
	global.__objectDepths[328] = -1; // obj_sparkletrail
	global.__objectDepths[329] = 0; // obj_sparkles_coin
	global.__objectDepths[330] = -7; // obj_smoke_cap
	global.__objectDepths[331] = -7; // obj_detroy_enemy
	global.__objectDepths[332] = -8; // obj_rotten_signal
	global.__objectDepths[333] = 0; // obj_gotas
	global.__objectDepths[334] = -12; // obj_splash_agua
	global.__objectDepths[335] = -12; // obj_splash_lava
	global.__objectDepths[336] = -12; // obj_splash_posion
	global.__objectDepths[337] = -16; // obj_menu_pausa
	global.__objectDepths[338] = -17; // obj_pausa_button
	global.__objectDepths[339] = 10; // obj_axe_smw
	global.__objectDepths[340] = 6; // obj_castle_floor
	global.__objectDepths[341] = 10; // obj_castle
	global.__objectDepths[342] = 10; // obj_castle_front
	global.__objectDepths[343] = -7; // obj_explosion
	global.__objectDepths[344] = 0; // obj_blockbumper
	global.__objectDepths[345] = 0; // obj_stomp
	global.__objectDepths[346] = -10; // obj_sidefade
	global.__objectDepths[347] = -26; // obj_title_controller
	global.__objectDepths[348] = -25; // obj_title_oprime
	global.__objectDepths[349] = -25; // obj_editor_screen
	global.__objectDepths[350] = -25; // obj_play_screen
	global.__objectDepths[351] = 0; // obj_load_level
	global.__objectDepths[352] = -100; // obj_mariostart
	global.__objectDepths[353] = -101; // obj_mariostart_m
	global.__objectDepths[354] = 0; // obj_intro_controller
	global.__objectDepths[355] = -1; // obj_mario_intro
	global.__objectDepths[356] = 0; // obj_shell_intro
	global.__objectDepths[357] = -18; // obj_settings_panel
	global.__objectDepths[358] = -19; // obj_configurar_controles
	global.__objectDepths[359] = -19; // obj_configurar_controles_reset
	global.__objectDepths[360] = -19; // obj_button_settings_estrella
	global.__objectDepths[361] = -19; // obj_button_settings_controls
	global.__objectDepths[362] = -19; // obj_button_settings_sombras
	global.__objectDepths[363] = -19; // obj_button_settings_idioma
	global.__objectDepths[364] = -19; // obj_button_settings_sm4j
	global.__objectDepths[365] = -19; // obj_selecting_player
	global.__objectDepths[366] = -19; // obj_window_select
	global.__objectDepths[367] = -19; // obj_button_settings_close
	global.__objectDepths[368] = -19; // obj_button_creditos
	global.__objectDepths[369] = -19; // obj_selecting_fps
	global.__objectDepths[370] = -19; // obj_st_slider
	global.__objectDepths[371] = -99; // obj_persistent
	global.__objectDepths[372] = 10; // obj_arrow_big
	global.__objectDepths[373] = -10; // obj_alert_message
	global.__objectDepths[374] = -16; // obj_alert_button
	global.__objectDepths[375] = -16; // obj_alert_close
	global.__objectDepths[376] = -6; // obj_guardabot
	global.__objectDepths[377] = 0; // obj_load_guardabot
	global.__objectDepths[378] = -5; // obj_gb_button
	global.__objectDepths[379] = -6; // obj_gb_level
	global.__objectDepths[380] = -7; // obj_bt_gb_play
	global.__objectDepths[381] = -7; // obj_bt_gb_delete
	global.__objectDepths[382] = -7; // obj_bt_gb_close
	global.__objectDepths[383] = -4; // obj_btn_reload
	global.__objectDepths[384] = -7; // obj_bt_pub
	global.__objectDepths[385] = -3; // obj_scrollbar2
	global.__objectDepths[386] = -22; // obj_iname_control
	global.__objectDepths[387] = -23; // obj_iname
	global.__objectDepths[388] = -23; // obj_bl2
	global.__objectDepths[389] = -23; // obj_iname_close
	global.__objectDepths[390] = -22; // obj_iname_control2
	global.__objectDepths[391] = -23; // obj_lun
	global.__objectDepths[392] = -23; // obj_lp
	global.__objectDepths[393] = -23; // obj_bl
	global.__objectDepths[394] = 0; // obj_login_control
	global.__objectDepths[395] = 0; // obj_version
	global.__objectDepths[396] = 0; // obj_btn_iniciar
	global.__objectDepths[397] = 0; // obj_btn_invitado
	global.__objectDepths[398] = 0; // obj_btn_social
	global.__objectDepths[399] = -20; // obj_superado_bg
	global.__objectDepths[400] = -22; // obj_continue_btn
	global.__objectDepths[401] = -21; // obj_button_superado
	global.__objectDepths[402] = -21; // obj_nm_like_heart
	global.__objectDepths[403] = -21; // obj_nm_dislike_heart
	global.__objectDepths[404] = -2; // obj_nm_card_expand
	global.__objectDepths[405] = -3; // obj_nm_card_close
	global.__objectDepths[406] = -3; // obj_nm_play
	global.__objectDepths[407] = 0; // obj_id_input
	global.__objectDepths[408] = -2; // obj_id_button
	global.__objectDepths[409] = -3; // obj_nm_button_retry_id
	global.__objectDepths[410] = 0; // obj_creator_input
	global.__objectDepths[411] = 0; // obj_creator_button
	global.__objectDepths[412] = -1; // obj_nivelesmundiales
	global.__objectDepths[413] = -2; // obj_nm_tabs
	global.__objectDepths[414] = 0; // obj_nm_card
	global.__objectDepths[415] = -3; // obj_scrollbar
	global.__objectDepths[416] = -2; // obj_pages_button
	global.__objectDepths[417] = -3; // obj_nm_button_retry
	global.__objectDepths[418] = -5; // obj_game_over
	global.__objectDepths[419] = -100; // obj_timeup
	global.__objectDepths[420] = 0; // obj_button_back
	global.__objectDepths[421] = 0; // cre_control
	global.__objectDepths[422] = -19; // obj_ccred
	global.__objectDepths[423] = -2; // obj_logo_c
	global.__objectDepths[424] = -11; // obj_apariencia
	global.__objectDepths[425] = -12; // obj_card_logo
	global.__objectDepths[426] = -11; // obj_bg_selection
	global.__objectDepths[427] = -12; // obj_bg1
	global.__objectDepths[428] = -11; // obj_time
	global.__objectDepths[429] = -12; // obj_button_ok
	global.__objectDepths[430] = -12; // obj_button_time
	global.__objectDepths[431] = -11; // obj_autoavance
	global.__objectDepths[432] = -12; // obj_button_autoavance
	global.__objectDepths[433] = -11; // obj_condiciones
	global.__objectDepths[434] = -12; // obj_condiciones_button
	global.__objectDepths[435] = -12; // obj_tabs_condiciones
	global.__objectDepths[436] = -25; // obj_alert_condicion
	global.__objectDepths[437] = -15; // obj_edit_menu
	global.__objectDepths[438] = -16; // obj_button_home
	global.__objectDepths[440] = -16; // obj_settings_button
	global.__objectDepths[441] = -16; // obj_button_close_menu
	global.__objectDepths[442] = 0; // obj_groundparent
	global.__objectDepths[443] = 10; // obj_ground2
	global.__objectDepths[444] = 300; // obj_ground3
	global.__objectDepths[445] = -11; // obj_panel_save_load
	global.__objectDepths[446] = -12; // obj_button_save_load
	global.__objectDepths[447] = -12; // obj_button_save_changes
	global.__objectDepths[448] = -15; // obj_alert_load
	global.__objectDepths[449] = -16; // obj_noti_load_button
	global.__objectDepths[450] = -16; // obj_load_btn_c
	global.__objectDepths[451] = -18; // obj_load_image
	global.__objectDepths[452] = -15; // obj_window_alert
	global.__objectDepths[453] = -16; // obj_button_notification_aceptar
	global.__objectDepths[454] = -16; // obj_button_notification_cancelar
	global.__objectDepths[455] = -16; // obj_input
	global.__objectDepths[456] = -18; // obj_toast
	global.__objectDepths[457] = -16; // obj_etiquetas
	global.__objectDepths[458] = 0; // obj_panelparent
	global.__objectDepths[459] = -14; // obj_creator_jugar_editar
	global.__objectDepths[460] = -10; // obj_menu_editor
	global.__objectDepths[461] = -10; // obj_menu_editor_ext
	global.__objectDepths[462] = -12; // obj_robot
	global.__objectDepths[463] = -10; // obj_erase
	global.__objectDepths[464] = -10; // obj_card_block_sounds
	global.__objectDepths[465] = -12; // obj_logo_game
	global.__objectDepths[466] = -12; // obj_card_bg
	global.__objectDepths[467] = -12; // obj_card_bout
	global.__objectDepths[468] = -12; // obj_card_autoavance
	global.__objectDepths[469] = -12; // obj_panel_time
	global.__objectDepths[470] = -12; // obj_card_condiciones
	global.__objectDepths[471] = -10; // obj_card_rocket
	global.__objectDepths[472] = -10; // obj_expand
	global.__objectDepths[473] = -10; // obj_dog
	global.__objectDepths[474] = -24; // obj_zoomclose
	global.__objectDepths[475] = -10; // obj_card_item
	global.__objectDepths[476] = -9; // obj_lave_draw
	global.__objectDepths[477] = -8; // obj_panel_left
	global.__objectDepths[478] = -12; // obj_night_change
	global.__objectDepths[479] = -10; // obj_expand_panels
	global.__objectDepths[480] = -10; // obj_expand_panels_left
	global.__objectDepths[481] = -10; // obj_expand_paneles_top
	global.__objectDepths[482] = 0; // obj_button_parent
	global.__objectDepths[483] = 0; // obj_panelsparent
	global.__objectDepths[484] = 299; // obj_decoracion_1
	global.__objectDepths[485] = 299; // obj_decoracion_2
	global.__objectDepths[486] = 299; // obj_decoracion_3
	global.__objectDepths[487] = 299; // obj_decoracion_4
	global.__objectDepths[488] = 0; // obj_decoracion_parent
	global.__objectDepths[489] = 280; // obj_modelbgo
	global.__objectDepths[490] = 5; // obj_modelsolid
	global.__objectDepths[491] = 280; // obj_modelbgo_dec
	global.__objectDepths[492] = 270; // obj_modelsizable
	global.__objectDepths[493] = 1; // obj_ground
	global.__objectDepths[494] = 0; // obj_tile_trigger
	global.__objectDepths[495] = 0; // obj_bowser_res
	global.__objectDepths[496] = 0; // obj_bowserjr_res
	global.__objectDepths[497] = 0; // obj_pswitch_res
	global.__objectDepths[498] = 0; // obj_pow_res
	global.__objectDepths[499] = 0; // obj_rock_res
	global.__objectDepths[500] = 0; // obj_pipebase_res
	global.__objectDepths[501] = 0; // obj_ice_res
	global.__objectDepths[502] = 0; // obj_coin_res
	global.__objectDepths[503] = 0; // obj_icecoin_res
	global.__objectDepths[504] = 0; // obj_pink_coin_res
	global.__objectDepths[505] = 0; // obj_coin10_res
	global.__objectDepths[506] = 0; // obj_coin30_res
	global.__objectDepths[507] = 0; // obj_coin50_res
	global.__objectDepths[508] = 0; // obj_key_res
	global.__objectDepths[509] = 0; // obj_goomba_res
	global.__objectDepths[510] = 0; // obj_goombrat_res
	global.__objectDepths[511] = -1; // obj_koopa_b_res
	global.__objectDepths[512] = -1; // obj_koopa_res
	global.__objectDepths[513] = -1; // obj_koopa_red_res
	global.__objectDepths[514] = -1; // obj_koopa_red_b_res
	global.__objectDepths[515] = 0; // obj_buzzybeetle_res
	global.__objectDepths[516] = 0; // obj_buzzybeetle_b_res
	global.__objectDepths[517] = 0; // obj_bonybeetle_res
	global.__objectDepths[518] = 0; // obj_bonybeetle_b_res
	global.__objectDepths[519] = 0; // obj_spiny_res
	global.__objectDepths[520] = 0; // obj_rocangrejo_res
	global.__objectDepths[521] = 0; // obj_tuberia_res
	global.__objectDepths[522] = 0; // obj_angrysun_res
	global.__objectDepths[523] = 0; // obj_floruga_res
	global.__objectDepths[524] = 0; // obj_floruga_angry_res
	global.__objectDepths[525] = 0; // obj_drybones_res
	global.__objectDepths[526] = 0; // obj_shell_drybones_res
	global.__objectDepths[527] = 0; // obj_spiny_shell_res
	global.__objectDepths[528] = 0; // obj_buzzy_shell_res
	global.__objectDepths[529] = 0; // obj_donut_res
	global.__objectDepths[530] = 0; // obj_blooper_res
	global.__objectDepths[531] = 0; // obj_lakitu_res
	global.__objectDepths[532] = 0; // obj_hammerbro_res
	global.__objectDepths[533] = 0; // obj_sledgebro_res
	global.__objectDepths[534] = 0; // obj_charginchuck_res
	global.__objectDepths[535] = 0; // obj_boomboom_res
	global.__objectDepths[536] = 0; // obj_thwomp_res
	global.__objectDepths[537] = 0; // obj_grrrol_res
	global.__objectDepths[538] = -1; // obj_grinder_res
	global.__objectDepths[539] = -1; // obj_bumper_res
	global.__objectDepths[540] = 0; // obj_bobomb_res
	global.__objectDepths[541] = 0; // obj_mechakoopa_res
	global.__objectDepths[542] = 0; // obj_bobomb_ready_res
	global.__objectDepths[543] = 0; // obj_bullebill_base_res
	global.__objectDepths[544] = 0; // obj_bullebill_base_red_res
	global.__objectDepths[545] = 0; // obj_cannon_res
	global.__objectDepths[546] = 0; // obj_cannon_red_res
	global.__objectDepths[547] = -1; // obj_soplete_res
	global.__objectDepths[548] = 0; // obj_monty_res
	global.__objectDepths[549] = 0; // obj_rocky_res
	global.__objectDepths[550] = 0; // obj_1up_res
	global.__objectDepths[551] = 0; // obj_mushroom_res
	global.__objectDepths[552] = 0; // obj_fireflower_res
	global.__objectDepths[553] = 0; // obj_frogsuit_res
	global.__objectDepths[554] = 0; // obj_hen_mushroom_res
	global.__objectDepths[555] = 0; // obj_superflower_res
	global.__objectDepths[556] = 0; // obj_cap_res
	global.__objectDepths[557] = 0; // obj_star_res
	global.__objectDepths[558] = 0; // obj_spring_res
	global.__objectDepths[559] = 0; // obj_spring_land_res
	global.__objectDepths[560] = 0; // obj_qblock_res
	global.__objectDepths[561] = 0; // obj_block_hidden_res
	global.__objectDepths[562] = 0; // obj_block_res
	global.__objectDepths[563] = 0; // obj_block_gold_res
	global.__objectDepths[564] = 0; // obj_noteblock_res
	global.__objectDepths[565] = 0; // obj_musicblock_res
	global.__objectDepths[566] = 0; // obj_noteblock_s_res
	global.__objectDepths[567] = 0; // obj_pplant_res
	global.__objectDepths[568] = 0; // obj_plant_fire_res
	global.__objectDepths[569] = -1; // obj_muncher_res
	global.__objectDepths[570] = -1; // obj_muncher_b_res
	global.__objectDepths[571] = 0; // obj_billbanzai_res
	global.__objectDepths[572] = 0; // obj_billbanzai_red_res
	global.__objectDepths[573] = 0; // obj_spike_res
	global.__objectDepths[574] = 0; // obj_spike_ball_res
	global.__objectDepths[575] = 0; // obj_torbellino_res
	global.__objectDepths[576] = 0; // obj_foo_res
	global.__objectDepths[577] = 0; // obj_onoffblock_res
	global.__objectDepths[578] = 0; // obj_onoffplatform_res
	global.__objectDepths[579] = 0; // obj_onoffplatform_blue_res
	global.__objectDepths[580] = 0; // obj_pblock_res
	global.__objectDepths[581] = 0; // obj_pblock2_res
	global.__objectDepths[582] = 0; // obj_chomp_res
	global.__objectDepths[583] = 0; // obj_boo_res
	global.__objectDepths[584] = 0; // obj_pinchos_res
	global.__objectDepths[585] = 0; // obj_nube_res
	global.__objectDepths[586] = 1; // obj_oneway_res
	global.__objectDepths[587] = 0; // obj_checkpoint_res
	global.__objectDepths[588] = 1; // obj_door_res
	global.__objectDepths[589] = 1; // obj_door_exit_res
	global.__objectDepths[590] = 1; // obj_door_switch_res
	global.__objectDepths[591] = 1; // obj_door_switch_exit_res
	global.__objectDepths[592] = 1; // obj_door_lock_res
	global.__objectDepths[593] = 1; // obj_door_lock_exit_res
	global.__objectDepths[594] = 0; // obj_clown_res
	global.__objectDepths[595] = 0; // obj_clown_fire_res
	global.__objectDepths[596] = 0; // obj_egg_res
	global.__objectDepths[597] = 0; // obj_egg_red_res
	global.__objectDepths[598] = 0; // obj_podoboo_res
	global.__objectDepths[599] = 0; // obj_podoboo_b_res
	global.__objectDepths[600] = 0; // obj_mini_icicle_res
	global.__objectDepths[601] = 0; // obj_mini_icicle2_res
	global.__objectDepths[602] = 0; // obj_icicle_res
	global.__objectDepths[603] = 0; // obj_icicle2_res
	global.__objectDepths[604] = 0; // obj_cheepcheep_res
	global.__objectDepths[605] = 0; // obj_cheepcheep2_res
	global.__objectDepths[606] = 0; // obj_arrow_res
	global.__objectDepths[607] = 0; // obj_magikoopa_res
	global.__objectDepths[608] = 0; // obj_lava_lift_res
	global.__objectDepths[609] = 0; // obj_fast_lava_lift_res
	global.__objectDepths[610] = 0; // obj_bouncycloud_res
	global.__objectDepths[611] = 2; // obj_vine_res
	global.__objectDepths[612] = 0; // obj_pokey_res
	global.__objectDepths[613] = 271; // obj_semisolid_platform1
	global.__objectDepths[614] = 8; // obj_mushroom_platform_res
	global.__objectDepths[615] = 8; // obj_puente_res
	global.__objectDepths[616] = -1; // obj_platform_res
	global.__objectDepths[617] = 0; // obj_platform_blue_res
	global.__objectDepths[618] = -1; // obj_firebar_res
	global.__objectDepths[619] = -7; // obj_efecto_sonido
	global.__objectDepths[620] = -7; // obj_efecto_musica
	global.__objectDepths[621] = 0; // obj_parent_sound_o
	global.__objectDepths[622] = 0; // obj_ubsi_or
	global.__objectDepths[623] = 0; // obj_ahh_or
	global.__objectDepths[624] = 0; // obj_risas_or
	global.__objectDepths[625] = 0; // obj_bebe_or
	global.__objectDepths[626] = 0; // obj_serpentina_or
	global.__objectDepths[627] = 0; // obj_aplausos_or
	global.__objectDepths[628] = 0; // obj_uhh_or
	global.__objectDepths[629] = 0; // obj_auh_or
	global.__objectDepths[630] = 0; // obj_bocina_or
	global.__objectDepths[631] = 0; // obj_cerdito_or
	global.__objectDepths[632] = 0; // obj_bombilla_or
	global.__objectDepths[633] = 0; // obj_error_or
	global.__objectDepths[634] = 0; // obj_nota_musical_or
	global.__objectDepths[635] = 0; // obj_remolino_or
	global.__objectDepths[636] = 0; // obj_fuegos_or
	global.__objectDepths[637] = 0; // obj_destello_or
	global.__objectDepths[638] = 0; // obj_golpe_gato_or
	global.__objectDepths[639] = 0; // obj_chisporreo_or
	global.__objectDepths[640] = -7; // obj_ubsi_snd_res
	global.__objectDepths[641] = -7; // obj_ahh_snd_res
	global.__objectDepths[642] = -7; // obj_risas_snd_res
	global.__objectDepths[643] = -7; // obj_bebe_snd_res
	global.__objectDepths[644] = -7; // obj_serpentina_snd_res
	global.__objectDepths[645] = -7; // obj_aplausos_snd_res
	global.__objectDepths[646] = -7; // obj_auh_snd_res
	global.__objectDepths[647] = -7; // obj_uhh_snd_res
	global.__objectDepths[648] = -7; // obj_bocina_snd_res
	global.__objectDepths[649] = -7; // obj_cerdito_snd_res
	global.__objectDepths[650] = -7; // obj_bombilla_snd_res
	global.__objectDepths[651] = -7; // obj_error_snd_res
	global.__objectDepths[652] = -7; // obj_nota_musical_snd_res
	global.__objectDepths[653] = -7; // obj_remolino_snd_res
	global.__objectDepths[654] = -7; // obj_fuegos_snd_res
	global.__objectDepths[655] = -7; // obj_destello_snd_res
	global.__objectDepths[656] = -7; // obj_golpe_gato_snd_res
	global.__objectDepths[657] = -7; // obj_chisporreteo_snd_res
	global.__objectDepths[658] = -10; // obj_panel_expand
	global.__objectDepths[659] = -11; // obj_button_close
	global.__objectDepths[660] = -11; // obj_next_before
	global.__objectDepths[661] = -11; // obj_panel_circle
	global.__objectDepths[662] = -12; // obj_card_circle
	global.__objectDepths[663] = -10; // obj_water_move
	global.__objectDepths[664] = -11; // obj_water_move_limit
	global.__objectDepths[665] = -11; // obj_bt_close_water
	global.__objectDepths[666] = -6; // obj_water_level_control
	global.__objectDepths[667] = -7; // obj_lava_water
	global.__objectDepths[668] = -20; // obj_lava_water_drybones
	global.__objectDepths[669] = -12; // obj_ventana_water
	global.__objectDepths[670] = -13; // obj_button_speed_water
	global.__objectDepths[671] = -19; // obj_ventana
	global.__objectDepths[672] = -20; // obj_window_button
	global.__objectDepths[673] = -20; // obj_button_wings
	global.__objectDepths[674] = -19; // obj_ventana_mario
	global.__objectDepths[675] = -20; // obj_window_mario_button
	global.__objectDepths[676] = -6; // obj_modo_sonidos_control
	global.__objectDepths[677] = -9; // obj_editormanager
	global.__objectDepths[678] = -7; // obj_mario_editor
	global.__objectDepths[679] = 0; // obj_parent_layout
	global.__objectDepths[680] = 0; // obj_parent_save
	global.__objectDepths[681] = 0; // obj_parent_resource
	global.__objectDepths[682] = 0; // obj_arrow_lock
	global.__objectDepths[683] = -7; // obj_parent_sounds
	global.__objectDepths[684] = 15; // obj_creation_preview
	global.__objectDepths[685] = 0; // obj_resource_empty
	global.__objectDepths[686] = -40; // obj_cursor
	global.__objectDepths[687] = 369; // obj_grid
	global.__objectDepths[688] = 0; // obj_player_trail
	global.__objectDepths[689] = -20; // obj_effect_touch
	global.__objectDepths[690] = -12; // obj_button_trail
	global.__objectDepths[691] = -12; // obj_button_sdog
	global.__objectDepths[692] = -23; // obj_change_view
	global.__objectDepths[693] = 0; // obj_parent_resource_block
	global.__objectDepths[694] = -16; // obj_profile
	global.__objectDepths[695] = 0; // obj_crystalorb
	global.__objectDepths[696] = 0; // obj_hawmask
	global.__objectDepths[697] = 100; // obj_DSM_control
	global.__objectDepths[698] = -5; // obj_DSM_button
	global.__objectDepths[699] = 0; // obj_DSM_level
	global.__objectDepths[700] = -1; // obj_DSM_mario
	global.__objectDepths[702] = -12; // obj_button_meteoritos
	global.__objectDepths[703] = -19; // obj_btn_settings_hd
	global.__objectDepths[704] = -7; // obj_bt_gb_edit
	global.__objectDepths[705] = 0; // obj_nm_style_game
	global.__objectDepths[706] = 0; // obj_nm_course_theme
	global.__objectDepths[707] = 0; // obj_nm_historial
	global.__objectDepths[708] = 0; // obj_nm_control
	global.__objectDepths[709] = 0; // obj_nm_orden
	global.__objectDepths[710] = -5; // obj_nm_button_big
	global.__objectDepths[711] = 0; // obj_nm_reaccion
	global.__objectDepths[712] = -3; // obj_nm_report
	global.__objectDepths[713] = 0; // obj_nm_search_btn
	global.__objectDepths[714] = 0; // obj_nm_input_text
	global.__objectDepths[715] = 0; // obj_nm_dificultad
	global.__objectDepths[716] = -3; // obj_nm_download
	global.__objectDepths[717] = -3; // obj_nm_star
	global.__objectDepths[718] = -3; // obj_nm_delete
	global.__objectDepths[719] = 0; // obj_nm_search_id_btn
	global.__objectDepths[720] = -3; // obj_btn_close_search
	global.__objectDepths[721] = 0; // obj_nm_tiempo
	global.__objectDepths[722] = -2; // obj_firebro
	global.__objectDepths[723] = 0; // obj_firebro_res
	global.__objectDepths[724] = 0; // obj_boomerangbro_res
	global.__objectDepths[725] = 0; // obj_boomerangbro
	global.__objectDepths[726] = -2; // obj_fireball_bro
	global.__objectDepths[727] = 0; // obj_icebro
	global.__objectDepths[728] = 0; // obj_icebro_res
	global.__objectDepths[729] = 9; // obj_skewer
	global.__objectDepths[730] = 0; // obj_skewer_res
	global.__objectDepths[731] = 0; // obj_skewertrunk
	global.__objectDepths[732] = -1; // obj_claw_res
	global.__objectDepths[733] = -1; // obj_claw
	global.__objectDepths[734] = -3; // obj_spike_ball_b
	global.__objectDepths[735] = 0; // obj_spike_ball_b_res
	global.__objectDepths[736] = 0; // obj_snow_ball_b
	global.__objectDepths[737] = -11; // obj_parcarry
	global.__objectDepths[738] = 0; // obj_snowball_bro
	global.__objectDepths[739] = -5; // obj_player_goal_smb2
	global.__objectDepths[740] = 0; // obj_frozenmario
	global.__objectDepths[741] = -8; // obj_puller
	global.__objectDepths[742] = 0; // obj_boomerang
	global.__objectDepths[743] = 0; // obj_cinta
	global.__objectDepths[744] = -1; // obj_cinta_on_res
	global.__objectDepths[745] = 0; // obj_cinta_parent
	global.__objectDepths[746] = -1; // obj_cinta_res
	global.__objectDepths[747] = 0; // obj_cinta_switch
	global.__objectDepths[748] = 0; // obj_meteorites_big
	global.__objectDepths[749] = 0; // obj_meteorites
	global.__objectDepths[750] = 0; // obj_meteorites_maker
	global.__objectDepths[751] = -7; // obj_n64_snd_res
	global.__objectDepths[752] = -7; // obj_bonus_snd_res
	global.__objectDepths[753] = 0; // obj_n64_or
	global.__objectDepths[754] = 0; // obj_efecto_musica_bonus
	global.__objectDepths[755] = 0; // obj_boss_or
	global.__objectDepths[756] = 0; // obj_bonus_or
	global.__objectDepths[757] = -7; // obj_boss_snd_res
	global.__objectDepths[758] = 0; // obj_shield_left
	global.__objectDepths[759] = -8; // obj_link_arrow_anim
	global.__objectDepths[760] = -8; // obj_link_dash_atack
	global.__objectDepths[761] = -8; // obj_link_down_atack
	global.__objectDepths[762] = -2; // obj_link
	global.__objectDepths[763] = 0; // obj_link_arrow
	global.__objectDepths[764] = -8; // obj_link_atack
	global.__objectDepths[765] = 0; // obj_link_bomb
	global.__objectDepths[766] = 0; // obj_link_res
	global.__objectDepths[767] = 0; // obj_shield_right
	global.__objectDepths[768] = -8; // obj_effect_link
	global.__objectDepths[769] = -19; // obj_settings_custom
	global.__objectDepths[770] = -19; // obj_settings_controls
	global.__objectDepths[771] = -19; // obj_button_settings_close2
	global.__objectDepths[772] = 0; // obj_boomboom_b_res
	global.__objectDepths[773] = -2; // obj_boomboom_b
	global.__objectDepths[774] = -7	// obj_chain_chomp_free_b
	global.__objectDepths[775] = -104	// obj_shadow
	global.__objectDepths[776] = -2	// obj_smoke
	global.__objectDepths[777] = 0; // obj_SMB2_mushroom_res
	global.__objectDepths[778] = 0; // obj_nm_refresh
	global.__objectDepths[779] = -11; // obj_header
	global.__objectDepths[780] = -11; // obj_btn_header_1
	global.__objectDepths[781] = -11; // obj_btn_header_2
	global.__objectDepths[782] = -11; // obj_btn_header_3
	global.__objectDepths[783] = -11; // obj_btn_header_4
	global.__objectDepths[784] = 0; // obj_cooligan
	global.__objectDepths[785] = 0; // obj_cooligan_res
	global.__objectDepths[786] = 0; // obj_goombrat_b_res
	global.__objectDepths[787] = 0; // obj_galoomba2_b
	global.__objectDepths[788] = -19; // obj_button_sombras
	global.__objectDepths[789] = -7; // obj_yoshi_blue
	global.__objectDepths[790] = -4; // obj_yoshi_runaway_blue
	global.__objectDepths[791] = -2; // obj_egg_blue
	global.__objectDepths[792] = 8; // obj_rails_res
	global.__objectDepths[793] = 5; // obj_DSM_clouds
	global.__objectDepths[794] = 0; // obj_DSM_control_game
	global.__objectDepths[795] = 0; // obj_grrrol_new_res
	global.__objectDepths[796] = 0; // obj_grrrol_b_res

	global.__objectNames[0] = "obj_lighting";
	global.__objectNames[1] = "obj_rainmaker";
	global.__objectNames[2] = "obj_snowmaker";
	global.__objectNames[3] = "obj_leafmaker";
	global.__objectNames[4] = "obj_firemaker";
	global.__objectNames[5] = "obj_flagpole";
	global.__objectNames[6] = "obj_SMB_flag";
	global.__objectNames[7] = "obj_NSMBU_flag_mario";
	global.__objectNames[8] = "obj_score_flag";
	global.__objectNames[9] = "obj_SMB_castle";
	global.__objectNames[10] = "obj_SMB_castle_front";
	global.__objectNames[11] = "obj_mini_flag";
	global.__objectNames[12] = "obj_goalcard";
	global.__objectNames[13] = "obj_goalcard_get";
	global.__objectNames[14] = "obj_goalgate";
	global.__objectNames[15] = "obj_goalgate_front";
	global.__objectNames[16] = "obj_goalgate_tape";
	global.__objectNames[17] = "obj_mario";
	global.__objectNames[18] = "obj_marioU";
	global.__objectNames[19] = "obj_checkpoint";
	global.__objectNames[20] = "obj_levelmanager";
	global.__objectNames[21] = "obj_autoscroll";
	global.__objectNames[22] = "obj_bganimator";
	global.__objectNames[23] = "obj_shake_mario";
	global.__objectNames[24] = "obj_platform_help";
	global.__objectNames[25] = "obj_fallow_view";
	global.__objectNames[26] = "obj_koopa_b";
	global.__objectNames[27] = "obj_koopa_red_b";
	global.__objectNames[28] = "obj_beachkoopa_b";
	global.__objectNames[29] = "obj_beachkoopa_red_b";
	global.__objectNames[30] = "obj_galoomba";
	global.__objectNames[31] = "obj_galoomba2";
	global.__objectNames[32] = "obj_koopa";
	global.__objectNames[33] = "obj_koopa_red";
	global.__objectNames[34] = "obj_beachkoopa";
	global.__objectNames[35] = "obj_beachkoopa_red";
	global.__objectNames[36] = "obj_floruga";
	global.__objectNames[37] = "obj_floruga_body";
	global.__objectNames[38] = "obj_goomba_swim";
	global.__objectNames[39] = "obj_buzzybeetle";
	global.__objectNames[40] = "obj_buzzybeetle_b";
	global.__objectNames[41] = "obj_spiny";
	global.__objectNames[42] = "obj_spiny_ball";
	global.__objectNames[43] = "obj_buzzy_ceiling";
	global.__objectNames[44] = "obj_jumppiranha";
	global.__objectNames[45] = "obj_piranhaplant";
	global.__objectNames[46] = "obj_plant_fire";
	global.__objectNames[47] = "obj_cheepcheep";
	global.__objectNames[48] = "obj_cheepcheep2";
	global.__objectNames[49] = "obj_blooper";
	global.__objectNames[50] = "obj_angrysun";
	global.__objectNames[51] = "obj_monty_chase";
	global.__objectNames[52] = "obj_spike";
	global.__objectNames[53] = "obj_spike_ball";
	global.__objectNames[54] = "obj_snow_ball";
	global.__objectNames[55] = "obj_snow_ball_held";
	global.__objectNames[56] = "obj_pokey";
	global.__objectNames[57] = "obj_lakitu";
	global.__objectNames[58] = "obj_spiny_thrown";
	global.__objectNames[59] = "obj_cloud_lakitu";
	global.__objectNames[60] = "obj_boo";
	global.__objectNames[61] = "obj_drybones";
	global.__objectNames[62] = "obj_bonybeetle";
	global.__objectNames[63] = "obj_bonybeetle_b";
	global.__objectNames[64] = "obj_thwomp";
	global.__objectNames[65] = "obj_grrrol";
	global.__objectNames[66] = "obj_podoboo";
	global.__objectNames[67] = "obj_podoboo_b";
	global.__objectNames[68] = "obj_grinder";
	global.__objectNames[69] = "obj_magikoopa";
	global.__objectNames[70] = "obj_firebar";
	global.__objectNames[71] = "obj_bobomb";
	global.__objectNames[72] = "obj_bobomb_ready";
	global.__objectNames[73] = "obj_bullebill_base";
	global.__objectNames[74] = "obj_bullebill_base_red";
	global.__objectNames[75] = "obj_bulletbill";
	global.__objectNames[76] = "obj_bulletbull_red";
	global.__objectNames[77] = "obj_banzaibill";
	global.__objectNames[78] = "obj_billbanzai_red";
	global.__objectNames[79] = "obj_cannon";
	global.__objectNames[80] = "obj_cannon_red";
	global.__objectNames[81] = "obj_soplete";
	global.__objectNames[82] = "obj_soplete_invert";
	global.__objectNames[83] = "obj_soplete_global";
	global.__objectNames[84] = "obj_soplete_invert_global";
	global.__objectNames[85] = "obj_chain_chomp_free";
	global.__objectNames[86] = "obj_foo";
	global.__objectNames[87] = "obj_foo_fog";
	global.__objectNames[88] = "obj_mechakoopa";
	global.__objectNames[89] = "obj_mechakoopa_held";
	global.__objectNames[90] = "obj_rocky";
	global.__objectNames[91] = "obj_rocangrejo";
	global.__objectNames[92] = "obj_SMB_bowser";
	global.__objectNames[93] = "obj_SMB3_bowser";
	global.__objectNames[94] = "obj_SMW_bowser";
	global.__objectNames[95] = "obj_NSMBU_bowser";
	global.__objectNames[96] = "obj_bowserjr";
	global.__objectNames[97] = "obj_NSMBU_bowserjr";
	global.__objectNames[98] = "obj_bowserjr_shell";
	global.__objectNames[99] = "obj_boomboom";
	global.__objectNames[100] = "obj_NSMBU_boomboom";
	global.__objectNames[101] = "obj_hammerbro";
	global.__objectNames[102] = "obj_sledgebro";
	global.__objectNames[103] = "obj_charginchuck";
	global.__objectNames[104] = "obj_wings_dead";
	global.__objectNames[105] = "obj_wings_dead_b";
	global.__objectNames[106] = "obj_paracaidas_dead";
	global.__objectNames[107] = "obj_paracaidas_go";
	global.__objectNames[108] = "obj_solid";
	global.__objectNames[109] = "obj_solidtop";
	global.__objectNames[110] = "obj_climb";
	global.__objectNames[111] = "obj_solidphy";
	global.__objectNames[112] = "obj_enabledsolid";
	global.__objectNames[113] = "obj_hurtsolid2";
	global.__objectNames[114] = "obj_solidhold";
	global.__objectNames[115] = "obj_solid_appear";
	global.__objectNames[116] = "obj_block";
	global.__objectNames[117] = "obj_block_multicoin";
	global.__objectNames[118] = "obj_block_coinchain";
	global.__objectNames[119] = "obj_block_hidden";
	global.__objectNames[120] = "obj_flipblock";
	global.__objectNames[121] = "obj_flipblock_anim";
	global.__objectNames[122] = "obj_block_gold";
	global.__objectNames[123] = "obj_noteblock";
	global.__objectNames[124] = "obj_musicblock";
	global.__objectNames[125] = "obj_noteblock_s";
	global.__objectNames[126] = "obj_onoffblock";
	global.__objectNames[127] = "obj_onoffplatform";
	global.__objectNames[128] = "obj_onoffplatform_blue";
	global.__objectNames[129] = "obj_block_rock";
	global.__objectNames[130] = "obj_block_ice";
	global.__objectNames[131] = "obj_pblock";
	global.__objectNames[132] = "obj_anti_pblock";
	global.__objectNames[133] = "obj_nube";
	global.__objectNames[134] = "obj_onoffplatform_d";
	global.__objectNames[135] = "obj_pipebase";
	global.__objectNames[136] = "obj_vine_green";
	global.__objectNames[137] = "obj_beanstalk";
	global.__objectNames[138] = "obj_vine";
	global.__objectNames[139] = "obj_muncher";
	global.__objectNames[140] = "obj_muncher_b";
	global.__objectNames[141] = "obj_pinchos";
	global.__objectNames[142] = "obj_mini_icicle";
	global.__objectNames[143] = "obj_mini_icicle2";
	global.__objectNames[144] = "obj_icicle";
	global.__objectNames[145] = "obj_icicle2";
	global.__objectNames[146] = "obj_arrow";
	global.__objectNames[147] = "obj_plataforma";
	global.__objectNames[148] = "obj_plataforma_blue";
	global.__objectNames[149] = "obj_donut";
	global.__objectNames[150] = "obj_fast_lava_lift";
	global.__objectNames[151] = "obj_lava_lift";
	global.__objectNames[152] = "obj_lava_lift_part";
	global.__objectNames[153] = "obj_bouncycloud";
	global.__objectNames[154] = "obj_coin";
	global.__objectNames[155] = "obj_icecoin";
	global.__objectNames[156] = "obj_pink_coin";
	global.__objectNames[157] = "obj_coin10";
	global.__objectNames[158] = "obj_coin30";
	global.__objectNames[159] = "obj_coin50";
	global.__objectNames[160] = "obj_spring";
	global.__objectNames[161] = "obj_spring_land";
	global.__objectNames[162] = "obj_coin_pow";
	global.__objectNames[163] = "obj_coin_pow_big";
	global.__objectNames[164] = "obj_pswitch";
	global.__objectNames[165] = "obj_pswitch_press";
	global.__objectNames[166] = "obj_block_pow_hold";
	global.__objectNames[167] = "obj_block_pow_active";
	global.__objectNames[168] = "obj_quicksand";
	global.__objectNames[169] = "obj_bumper";
	global.__objectNames[170] = "obj_onewaygate_right";
	global.__objectNames[171] = "obj_onewaygate_left";
	global.__objectNames[172] = "obj_onewaygate_top";
	global.__objectNames[173] = "obj_onewaygate_bottom";
	global.__objectNames[174] = "obj_key";
	global.__objectNames[175] = "obj_key_appear";
	global.__objectNames[176] = "obj_key_fallow";
	global.__objectNames[177] = "obj_torbellino";
	global.__objectNames[178] = "obj_bortice";
	global.__objectNames[179] = "obj_door";
	global.__objectNames[180] = "obj_door_exit";
	global.__objectNames[181] = "obj_door_switch";
	global.__objectNames[182] = "obj_door_switch_exit";
	global.__objectNames[183] = "obj_door_lock";
	global.__objectNames[184] = "obj_door_lock_exit";
	global.__objectNames[185] = "obj_tuberia";
	global.__objectNames[186] = "obj_deactivation";
	global.__objectNames[187] = "obj_physicsparent";
	global.__objectNames[188] = "obj_powerupparent";
	global.__objectNames[189] = "obj_enemyparent";
	global.__objectNames[190] = "obj_deactenemyparent";
	global.__objectNames[191] = "obj_bossparent";
	global.__objectNames[192] = "obj_player_goal_parent";
	global.__objectNames[193] = "obj_blockparent";
	global.__objectNames[194] = "obj_rockparent";
	global.__objectNames[195] = "obj_holdparent";
	global.__objectNames[196] = "obj_slopeparent";
	global.__objectNames[197] = "obj_enemyparent_held";
	global.__objectNames[198] = "obj_enemyparent_lava";
	global.__objectNames[199] = "obj_platform_parent";
	global.__objectNames[200] = "obj_physicssolid";
	global.__objectNames[201] = "obj_deadmario";
	global.__objectNames[202] = "obj_mario_temp";
	global.__objectNames[203] = "obj_doormario";
	global.__objectNames[204] = "obj_doormario_exit";
	global.__objectNames[205] = "obj_player_warp";
	global.__objectNames[206] = "obj_mario_pballon";
	global.__objectNames[207] = "obj_player_goal_smb1";
	global.__objectNames[208] = "obj_player_goal_smb3";
	global.__objectNames[209] = "obj_player_goal_smw";
	global.__objectNames[210] = "obj_player_goal_smw_castle";
	global.__objectNames[211] = "obj_player_goal_nsmbu";
	global.__objectNames[212] = "obj_slider";
	global.__objectNames[213] = "obj_spinner";
	global.__objectNames[214] = "obj_mario_transform2";
	global.__objectNames[215] = "obj_penguin_attack";
	global.__objectNames[216] = "obj_groundpount";
	global.__objectNames[217] = "obj_icon_dead";
	global.__objectNames[218] = "obj_1up";
	global.__objectNames[219] = "obj_mushroom";
	global.__objectNames[220] = "obj_fireflower";
	global.__objectNames[221] = "obj_superflower";
	global.__objectNames[222] = "obj_cap";
	global.__objectNames[223] = "obj_megamushroom";
	global.__objectNames[224] = "obj_hen_mushroom";
	global.__objectNames[225] = "obj_pballon";
	global.__objectNames[226] = "obj_star";
	global.__objectNames[227] = "obj_propellershroom";
	global.__objectNames[228] = "obj_frogsuit";
	global.__objectNames[229] = "obj_hammersuit";
	global.__objectNames[230] = "obj_penguin_suit";
	global.__objectNames[231] = "obj_superarcon";
	global.__objectNames[232] = "obj_egg";
	global.__objectNames[233] = "obj_egg_hatch";
	global.__objectNames[234] = "obj_yoshi2";
	global.__objectNames[235] = "obj_yoshi_runaway";
	global.__objectNames[236] = "obj_yoshi_abandon";
	global.__objectNames[237] = "obj_yoshifire";
	global.__objectNames[238] = "obj_yoshifire_purple";
	global.__objectNames[239] = "obj_yoshifire_one";
	global.__objectNames[240] = "obj_tongue";
	global.__objectNames[241] = "obj_egg_red";
	global.__objectNames[242] = "obj_yoshi_red";
	global.__objectNames[243] = "obj_yoshi_runaway_red";
	global.__objectNames[244] = "obj_getshoe";
	global.__objectNames[245] = "obj_kuriboshoe";
	global.__objectNames[246] = "obj_kuriboshoe2";
	global.__objectNames[247] = "obj_smoke_shoe";
	global.__objectNames[248] = "obj_kuriboshoe_movement";
	global.__objectNames[249] = "obj_kuribo_drybones";
	global.__objectNames[250] = "obj_helmet";
	global.__objectNames[251] = "obj_helmet_spiny";
	global.__objectNames[252] = "obj_brickhelmet";
	global.__objectNames[253] = "obj_clown";
	global.__objectNames[254] = "obj_clown_fire";
	global.__objectNames[255] = "obj_fire_clown";
	global.__objectNames[256] = "obj_fire_clown_small";
	global.__objectNames[257] = "obj_clown_explotion";
	global.__objectNames[258] = "obj_cap_mario";
	global.__objectNames[259] = "obj_powerupsprout";
	global.__objectNames[260] = "obj_powerupsprout_note";
	global.__objectNames[261] = "obj_fireball";
	global.__objectNames[262] = "obj_fireball_b";
	global.__objectNames[263] = "obj_snowball";
	global.__objectNames[264] = "obj_superball";
	global.__objectNames[265] = "obj_superball_trail";
	global.__objectNames[266] = "obj_invincibility";
	global.__objectNames[267] = "obj_brohammer_yoshi";
	global.__objectNames[268] = "obj_bones_yoshi";
	global.__objectNames[269] = "obj_bones_yoshi_one";
	global.__objectNames[270] = "obj_hammer";
	global.__objectNames[271] = "obj_hammer_b";
	global.__objectNames[272] = "obj_gold_explosion";
	global.__objectNames[273] = "obj_galoomba_hold";
	global.__objectNames[274] = "obj_galoomba_hold2";
	global.__objectNames[275] = "obj_plantfire";
	global.__objectNames[276] = "obj_espina";
	global.__objectNames[277] = "obj_angrysun_movement";
	global.__objectNames[278] = "obj_crumblebones";
	global.__objectNames[279] = "obj_crumblebony";
	global.__objectNames[280] = "obj_crumblebony_b";
	global.__objectNames[281] = "obj_magic";
	global.__objectNames[282] = "obj_bone";
	global.__objectNames[283] = "obj_bobomb_hold";
	global.__objectNames[284] = "obj_cannonball";
	global.__objectNames[285] = "obj_cannonball_red";
	global.__objectNames[286] = "obj_wrench";
	global.__objectNames[287] = "obj_rorock";
	global.__objectNames[288] = "obj_bowser_fire";
	global.__objectNames[289] = "obj_NSMBU_bowser_fire";
	global.__objectNames[290] = "obj_NSMBU_bowser_fire_up";
	global.__objectNames[291] = "obj_bowserfire_up";
	global.__objectNames[292] = "obj_bowser_fire_down";
	global.__objectNames[293] = "obj_bowserjr_fire";
	global.__objectNames[294] = "obj_NSMBU_bowserjr_fire";
	global.__objectNames[295] = "obj_enemy_dead";
	global.__objectNames[296] = "obj_bowser_dead";
	global.__objectNames[297] = "obj_enemy_dead_castle";
	global.__objectNames[298] = "obj_bowser_dead_castle";
	global.__objectNames[299] = "obj_bowserjr_dead_castle";
	global.__objectNames[300] = "obj_enemy_multidead";
	global.__objectNames[301] = "obj_stomped";
	global.__objectNames[302] = "obj_shell";
	global.__objectNames[303] = "obj_shell_held";
	global.__objectNames[304] = "obj_shell_empty";
	global.__objectNames[305] = "obj_spiny_empty";
	global.__objectNames[306] = "obj_shell_drybones";
	global.__objectNames[307] = "obj_shell_drybones_held";
	global.__objectNames[308] = "obj_brohammer";
	global.__objectNames[309] = "obj_enemyfrozen";
	global.__objectNames[310] = "obj_blockcoin";
	global.__objectNames[311] = "obj_coinchain";
	global.__objectNames[312] = "obj_shard";
	global.__objectNames[313] = "obj_veggiecoin";
	global.__objectNames[314] = "obj_multiveggiecoin";
	global.__objectNames[315] = "obj_coinchange";
	global.__objectNames[316] = "obj_blownbubble";
	global.__objectNames[317] = "obj_curtainin";
	global.__objectNames[318] = "obj_curtainout";
	global.__objectNames[319] = "obj_fadein";
	global.__objectNames[320] = "obj_fadeout";
	global.__objectNames[321] = "obj_score";
	global.__objectNames[322] = "obj_smoke";
	global.__objectNames[323] = "obj_smoke_steps";
	global.__objectNames[324] = "obj_statuesmoke";
	global.__objectNames[325] = "obj_spinsmoke";
	global.__objectNames[326] = "obj_spinthump";
	global.__objectNames[327] = "obj_bubble";
	global.__objectNames[328] = "obj_sparkletrail";
	global.__objectNames[329] = "obj_sparkles_coin";
	global.__objectNames[330] = "obj_smoke_cap";
	global.__objectNames[331] = "obj_detroy_enemy";
	global.__objectNames[332] = "obj_rotten_signal";
	global.__objectNames[333] = "obj_gotas";
	global.__objectNames[334] = "obj_splash_agua";
	global.__objectNames[335] = "obj_splash_lava";
	global.__objectNames[336] = "obj_splash_posion";
	global.__objectNames[337] = "obj_menu_pausa";
	global.__objectNames[338] = "obj_pausa_button";
	global.__objectNames[339] = "obj_axe_smw";
	global.__objectNames[340] = "obj_castle_floor";
	global.__objectNames[341] = "obj_castle";
	global.__objectNames[342] = "obj_castle_front";
	global.__objectNames[343] = "obj_explosion";
	global.__objectNames[344] = "obj_blockbumper";
	global.__objectNames[345] = "obj_stomp";
	global.__objectNames[346] = "obj_sidefade";
	global.__objectNames[347] = "obj_title_controller";
	global.__objectNames[348] = "obj_title_oprime";
	global.__objectNames[349] = "obj_editor_screen";
	global.__objectNames[350] = "obj_play_screen";
	global.__objectNames[351] = "obj_load_level";
	global.__objectNames[352] = "obj_mariostart";
	global.__objectNames[353] = "obj_mariostart_m";
	global.__objectNames[354] = "obj_intro_controller";
	global.__objectNames[355] = "obj_mario_intro";
	global.__objectNames[356] = "obj_shell_intro";
	global.__objectNames[357] = "obj_settings_panel";
	global.__objectNames[358] = "obj_configurar_controles";
	global.__objectNames[359] = "obj_configurar_controles_reset";
	global.__objectNames[360] = "obj_button_settings_estrella";
	global.__objectNames[361] = "obj_button_settings_controls";
	global.__objectNames[362] = "obj_button_settings_sombras";
	global.__objectNames[363] = "obj_button_settings_idioma";
	global.__objectNames[364] = "obj_button_settings_sm4j";
	global.__objectNames[365] = "obj_selecting_player";
	global.__objectNames[366] = "obj_window_select";
	global.__objectNames[367] = "obj_button_settings_close";
	global.__objectNames[368] = "obj_button_creditos";
	global.__objectNames[369] = "obj_selecting_fps";
	global.__objectNames[370] = "obj_st_slider";
	global.__objectNames[371] = "obj_persistent";
	global.__objectNames[372] = "obj_arrow_big";
	global.__objectNames[373] = "obj_alert_message";
	global.__objectNames[374] = "obj_alert_button";
	global.__objectNames[375] = "obj_alert_close";
	global.__objectNames[376] = "obj_guardabot";
	global.__objectNames[377] = "obj_load_guardabot";
	global.__objectNames[378] = "obj_gb_button";
	global.__objectNames[379] = "obj_gb_level";
	global.__objectNames[380] = "obj_bt_gb_play";
	global.__objectNames[381] = "obj_bt_gb_delete";
	global.__objectNames[382] = "obj_bt_gb_close";
	global.__objectNames[383] = "obj_btn_reload";
	global.__objectNames[384] = "obj_bt_pub";
	global.__objectNames[385] = "obj_scrollbar2";
	global.__objectNames[386] = "obj_iname_control";
	global.__objectNames[387] = "obj_iname";
	global.__objectNames[388] = "obj_bl2";
	global.__objectNames[389] = "obj_iname_close";
	global.__objectNames[390] = "obj_iname_control2";
	global.__objectNames[391] = "obj_lun";
	global.__objectNames[392] = "obj_lp";
	global.__objectNames[393] = "obj_bl";
	global.__objectNames[394] = "obj_login_control";
	global.__objectNames[395] = "obj_version";
	global.__objectNames[396] = "obj_btn_iniciar";
	global.__objectNames[397] = "obj_btn_invitado";
	global.__objectNames[398] = "obj_btn_social";
	global.__objectNames[399] = "obj_superado_bg";
	global.__objectNames[400] = "obj_continue_btn";
	global.__objectNames[401] = "obj_button_superado";
	global.__objectNames[402] = "obj_nm_like_heart";
	global.__objectNames[403] = "obj_nm_dislike_heart";
	global.__objectNames[404] = "obj_nm_card_expand";
	global.__objectNames[405] = "obj_nm_card_close";
	global.__objectNames[406] = "obj_nm_play";
	global.__objectNames[407] = "obj_id_input";
	global.__objectNames[408] = "obj_id_button";
	global.__objectNames[409] = "obj_nm_button_retry_id";
	global.__objectNames[410] = "obj_creator_input";
	global.__objectNames[411] = "obj_creator_button";
	global.__objectNames[412] = "obj_nivelesmundiales";
	global.__objectNames[413] = "obj_nm_tabs";
	global.__objectNames[414] = "obj_nm_card";
	global.__objectNames[415] = "obj_scrollbar";
	global.__objectNames[416] = "obj_pages_button";
	global.__objectNames[417] = "obj_nm_button_retry";
	global.__objectNames[418] = "obj_game_over";
	global.__objectNames[419] = "obj_timeup";
	global.__objectNames[420] = "obj_button_back";
	global.__objectNames[421] = "cre_control";
	global.__objectNames[422] = "obj_ccred";
	global.__objectNames[423] = "obj_logo_c";
	global.__objectNames[424] = "obj_apariencia";
	global.__objectNames[425] = "obj_card_logo";
	global.__objectNames[426] = "obj_bg_selection";
	global.__objectNames[427] = "obj_bg1";
	global.__objectNames[428] = "obj_time";
	global.__objectNames[429] = "obj_button_ok";
	global.__objectNames[430] = "obj_button_time";
	global.__objectNames[431] = "obj_autoavance";
	global.__objectNames[432] = "obj_button_autoavance";
	global.__objectNames[433] = "obj_condiciones";
	global.__objectNames[434] = "obj_condiciones_button";
	global.__objectNames[435] = "obj_tabs_condiciones";
	global.__objectNames[436] = "obj_alert_condicion";
	global.__objectNames[437] = "obj_edit_menu";
	global.__objectNames[438] = "obj_button_home";
	global.__objectNames[440] = "obj_settings_button";
	global.__objectNames[441] = "obj_button_close_menu";
	global.__objectNames[442] = "obj_groundparent";
	global.__objectNames[443] = "obj_ground2";
	global.__objectNames[444] = "obj_ground3";
	global.__objectNames[445] = "obj_panel_save_load";
	global.__objectNames[446] = "obj_button_save_load";
	global.__objectNames[447] = "obj_button_save_changes";
	global.__objectNames[448] = "obj_alert_load";
	global.__objectNames[449] = "obj_noti_load_button";
	global.__objectNames[450] = "obj_load_btn_c";
	global.__objectNames[451] = "obj_load_image";
	global.__objectNames[452] = "obj_window_alert";
	global.__objectNames[453] = "obj_button_notification_aceptar";
	global.__objectNames[454] = "obj_button_notification_cancelar";
	global.__objectNames[455] = "obj_input";
	global.__objectNames[456] = "obj_toast";
	global.__objectNames[457] = "obj_etiquetas";
	global.__objectNames[458] = "obj_panelparent";
	global.__objectNames[459] = "obj_creator_jugar_editar";
	global.__objectNames[460] = "obj_menu_editor";
	global.__objectNames[461] = "obj_menu_editor_ext";
	global.__objectNames[462] = "obj_robot";
	global.__objectNames[463] = "obj_erase";
	global.__objectNames[464] = "obj_card_block_sounds";
	global.__objectNames[465] = "obj_logo_game";
	global.__objectNames[466] = "obj_card_bg";
	global.__objectNames[467] = "obj_card_bout";
	global.__objectNames[468] = "obj_card_autoavance";
	global.__objectNames[469] = "obj_panel_time";
	global.__objectNames[470] = "obj_card_condiciones";
	global.__objectNames[471] = "obj_card_rocket";
	global.__objectNames[472] = "obj_expand";
	global.__objectNames[473] = "obj_dog";
	global.__objectNames[474] = "obj_zoomclose";
	global.__objectNames[475] = "obj_card_item";
	global.__objectNames[476] = "obj_lave_draw";
	global.__objectNames[477] = "obj_panel_left";
	global.__objectNames[478] = "obj_night_change";
	global.__objectNames[479] = "obj_expand_panels";
	global.__objectNames[480] = "obj_expand_panels_left";
	global.__objectNames[481] = "obj_expand_paneles_top";
	global.__objectNames[482] = "obj_button_parent";
	global.__objectNames[483] = "obj_panelsparent";
	global.__objectNames[484] = "obj_decoracion_1";
	global.__objectNames[485] = "obj_decoracion_2";
	global.__objectNames[486] = "obj_decoracion_3";
	global.__objectNames[487] = "obj_decoracion_4";
	global.__objectNames[488] = "obj_decoracion_parent";
	global.__objectNames[489] = "obj_modelbgo";
	global.__objectNames[490] = "obj_modelsolid";
	global.__objectNames[491] = "obj_modelbgo_dec";
	global.__objectNames[492] = "obj_modelsizable";
	global.__objectNames[493] = "obj_ground";
	global.__objectNames[494] = "obj_tile_trigger";
	global.__objectNames[495] = "obj_bowser_res";
	global.__objectNames[496] = "obj_bowserjr_res";
	global.__objectNames[497] = "obj_pswitch_res";
	global.__objectNames[498] = "obj_pow_res";
	global.__objectNames[499] = "obj_rock_res";
	global.__objectNames[500] = "obj_pipebase_res";
	global.__objectNames[501] = "obj_ice_res";
	global.__objectNames[502] = "obj_coin_res";
	global.__objectNames[503] = "obj_icecoin_res";
	global.__objectNames[504] = "obj_pink_coin_res";
	global.__objectNames[505] = "obj_coin10_res";
	global.__objectNames[506] = "obj_coin30_res";
	global.__objectNames[507] = "obj_coin50_res";
	global.__objectNames[508] = "obj_key_res";
	global.__objectNames[509] = "obj_goomba_res";
	global.__objectNames[510] = "obj_goombrat_res";
	global.__objectNames[511] = "obj_koopa_b_res";
	global.__objectNames[512] = "obj_koopa_res";
	global.__objectNames[513] = "obj_koopa_red_res";
	global.__objectNames[514] = "obj_koopa_red_b_res";
	global.__objectNames[515] = "obj_buzzybeetle_res";
	global.__objectNames[516] = "obj_buzzybeetle_b_res";
	global.__objectNames[517] = "obj_bonybeetle_res";
	global.__objectNames[518] = "obj_bonybeetle_b_res";
	global.__objectNames[519] = "obj_spiny_res";
	global.__objectNames[520] = "obj_rocangrejo_res";
	global.__objectNames[521] = "obj_tuberia_res";
	global.__objectNames[522] = "obj_angrysun_res";
	global.__objectNames[523] = "obj_floruga_res";
	global.__objectNames[524] = "obj_floruga_angry_res";
	global.__objectNames[525] = "obj_drybones_res";
	global.__objectNames[526] = "obj_shell_drybones_res";
	global.__objectNames[527] = "obj_spiny_shell_res";
	global.__objectNames[528] = "obj_buzzy_shell_res";
	global.__objectNames[529] = "obj_donut_res";
	global.__objectNames[530] = "obj_blooper_res";
	global.__objectNames[531] = "obj_lakitu_res";
	global.__objectNames[532] = "obj_hammerbro_res";
	global.__objectNames[533] = "obj_sledgebro_res";
	global.__objectNames[534] = "obj_charginchuck_res";
	global.__objectNames[535] = "obj_boomboom_res";
	global.__objectNames[536] = "obj_thwomp_res";
	global.__objectNames[537] = "obj_grrrol_res";
	global.__objectNames[538] = "obj_grinder_res";
	global.__objectNames[539] = "obj_bumper_res";
	global.__objectNames[540] = "obj_bobomb_res";
	global.__objectNames[541] = "obj_mechakoopa_res";
	global.__objectNames[542] = "obj_bobomb_ready_res";
	global.__objectNames[543] = "obj_bullebill_base_res";
	global.__objectNames[544] = "obj_bullebill_base_red_res";
	global.__objectNames[545] = "obj_cannon_res";
	global.__objectNames[546] = "obj_cannon_red_res";
	global.__objectNames[547] = "obj_soplete_res";
	global.__objectNames[548] = "obj_monty_res";
	global.__objectNames[549] = "obj_rocky_res";
	global.__objectNames[550] = "obj_1up_res";
	global.__objectNames[551] = "obj_mushroom_res";
	global.__objectNames[552] = "obj_fireflower_res";
	global.__objectNames[553] = "obj_frogsuit_res";
	global.__objectNames[554] = "obj_hen_mushroom_res";
	global.__objectNames[555] = "obj_superflower_res";
	global.__objectNames[556] = "obj_cap_res";
	global.__objectNames[557] = "obj_star_res";
	global.__objectNames[558] = "obj_spring_res";
	global.__objectNames[559] = "obj_spring_land_res";
	global.__objectNames[560] = "obj_qblock_res";
	global.__objectNames[561] = "obj_block_hidden_res";
	global.__objectNames[562] = "obj_block_res";
	global.__objectNames[563] = "obj_block_gold_res";
	global.__objectNames[564] = "obj_noteblock_res";
	global.__objectNames[565] = "obj_musicblock_res";
	global.__objectNames[566] = "obj_noteblock_s_res";
	global.__objectNames[567] = "obj_pplant_res";
	global.__objectNames[568] = "obj_plant_fire_res";
	global.__objectNames[569] = "obj_muncher_res";
	global.__objectNames[570] = "obj_muncher_b_res";
	global.__objectNames[571] = "obj_billbanzai_res";
	global.__objectNames[572] = "obj_billbanzai_red_res";
	global.__objectNames[573] = "obj_spike_res";
	global.__objectNames[574] = "obj_spike_ball_res";
	global.__objectNames[575] = "obj_torbellino_res";
	global.__objectNames[576] = "obj_foo_res";
	global.__objectNames[577] = "obj_onoffblock_res";
	global.__objectNames[578] = "obj_onoffplatform_res";
	global.__objectNames[579] = "obj_onoffplatform_blue_res";
	global.__objectNames[580] = "obj_pblock_res";
	global.__objectNames[581] = "obj_pblock2_res";
	global.__objectNames[582] = "obj_chomp_res";
	global.__objectNames[583] = "obj_boo_res";
	global.__objectNames[584] = "obj_pinchos_res";
	global.__objectNames[585] = "obj_nube_res";
	global.__objectNames[586] = "obj_oneway_res";
	global.__objectNames[587] = "obj_checkpoint_res";
	global.__objectNames[588] = "obj_door_res";
	global.__objectNames[589] = "obj_door_exit_res";
	global.__objectNames[590] = "obj_door_switch_res";
	global.__objectNames[591] = "obj_door_switch_exit_res";
	global.__objectNames[592] = "obj_door_lock_res";
	global.__objectNames[593] = "obj_door_lock_exit_res";
	global.__objectNames[594] = "obj_clown_res";
	global.__objectNames[595] = "obj_clown_fire_res";
	global.__objectNames[596] = "obj_egg_res";
	global.__objectNames[597] = "obj_egg_red_res";
	global.__objectNames[598] = "obj_podoboo_res";
	global.__objectNames[599] = "obj_podoboo_b_res";
	global.__objectNames[600] = "obj_mini_icicle_res";
	global.__objectNames[601] = "obj_mini_icicle2_res";
	global.__objectNames[602] = "obj_icicle_res";
	global.__objectNames[603] = "obj_icicle2_res";
	global.__objectNames[604] = "obj_cheepcheep_res";
	global.__objectNames[605] = "obj_cheepcheep2_res";
	global.__objectNames[606] = "obj_arrow_res";
	global.__objectNames[607] = "obj_magikoopa_res";
	global.__objectNames[608] = "obj_lava_lift_res";
	global.__objectNames[609] = "obj_fast_lava_lift_res";
	global.__objectNames[610] = "obj_bouncycloud_res";
	global.__objectNames[611] = "obj_vine_res";
	global.__objectNames[612] = "obj_pokey_res";
	global.__objectNames[613] = "obj_semisolid_platform1";
	global.__objectNames[614] = "obj_mushroom_platform_res";
	global.__objectNames[615] = "obj_puente_res";
	global.__objectNames[616] = "obj_platform_res";
	global.__objectNames[617] = "obj_platform_blue_res";
	global.__objectNames[618] = "obj_firebar_res";
	global.__objectNames[619] = "obj_efecto_sonido";
	global.__objectNames[620] = "obj_efecto_musica";
	global.__objectNames[621] = "obj_parent_sound_o";
	global.__objectNames[622] = "obj_ubsi_or";
	global.__objectNames[623] = "obj_ahh_or";
	global.__objectNames[624] = "obj_risas_or";
	global.__objectNames[625] = "obj_bebe_or";
	global.__objectNames[626] = "obj_serpentina_or";
	global.__objectNames[627] = "obj_aplausos_or";
	global.__objectNames[628] = "obj_uhh_or";
	global.__objectNames[629] = "obj_auh_or";
	global.__objectNames[630] = "obj_bocina_or";
	global.__objectNames[631] = "obj_cerdito_or";
	global.__objectNames[632] = "obj_bombilla_or";
	global.__objectNames[633] = "obj_error_or";
	global.__objectNames[634] = "obj_nota_musical_or";
	global.__objectNames[635] = "obj_remolino_or";
	global.__objectNames[636] = "obj_fuegos_or";
	global.__objectNames[637] = "obj_destello_or";
	global.__objectNames[638] = "obj_golpe_gato_or";
	global.__objectNames[639] = "obj_chisporreo_or";
	global.__objectNames[640] = "obj_ubsi_snd_res";
	global.__objectNames[641] = "obj_ahh_snd_res";
	global.__objectNames[642] = "obj_risas_snd_res";
	global.__objectNames[643] = "obj_bebe_snd_res";
	global.__objectNames[644] = "obj_serpentina_snd_res";
	global.__objectNames[645] = "obj_aplausos_snd_res";
	global.__objectNames[646] = "obj_auh_snd_res";
	global.__objectNames[647] = "obj_uhh_snd_res";
	global.__objectNames[648] = "obj_bocina_snd_res";
	global.__objectNames[649] = "obj_cerdito_snd_res";
	global.__objectNames[650] = "obj_bombilla_snd_res";
	global.__objectNames[651] = "obj_error_snd_res";
	global.__objectNames[652] = "obj_nota_musical_snd_res";
	global.__objectNames[653] = "obj_remolino_snd_res";
	global.__objectNames[654] = "obj_fuegos_snd_res";
	global.__objectNames[655] = "obj_destello_snd_res";
	global.__objectNames[656] = "obj_golpe_gato_snd_res";
	global.__objectNames[657] = "obj_chisporreteo_snd_res";
	global.__objectNames[658] = "obj_panel_expand";
	global.__objectNames[659] = "obj_button_close";
	global.__objectNames[660] = "obj_next_before";
	global.__objectNames[661] = "obj_panel_circle";
	global.__objectNames[662] = "obj_card_circle";
	global.__objectNames[663] = "obj_water_move";
	global.__objectNames[664] = "obj_water_move_limit";
	global.__objectNames[665] = "obj_bt_close_water";
	global.__objectNames[666] = "obj_water_level_control";
	global.__objectNames[667] = "obj_lava_water";
	global.__objectNames[668] = "obj_lava_water_drybones";
	global.__objectNames[669] = "obj_ventana_water";
	global.__objectNames[670] = "obj_button_speed_water";
	global.__objectNames[671] = "obj_ventana";
	global.__objectNames[672] = "obj_window_button";
	global.__objectNames[673] = "obj_button_wings";
	global.__objectNames[674] = "obj_ventana_mario";
	global.__objectNames[675] = "obj_window_mario_button";
	global.__objectNames[676] = "obj_modo_sonidos_control";
	global.__objectNames[677] = "obj_editormanager";
	global.__objectNames[678] = "obj_mario_editor";
	global.__objectNames[679] = "obj_parent_layout";
	global.__objectNames[680] = "obj_parent_save";
	global.__objectNames[681] = "obj_parent_resource";
	global.__objectNames[682] = "obj_arrow_lock";
	global.__objectNames[683] = "obj_parent_sounds";
	global.__objectNames[684] = "obj_creation_preview";
	global.__objectNames[685] = "obj_resource_empty";
	global.__objectNames[686] = "obj_cursor";
	global.__objectNames[687] = "obj_grid";
	global.__objectNames[688] = "obj_player_trail";
	global.__objectNames[689] = "obj_effect_touch";
	global.__objectNames[690] = "obj_button_trail";
	global.__objectNames[691] = "obj_button_sdog";
	global.__objectNames[692] = "obj_change_view";
	global.__objectNames[693] = "obj_parent_resource_block";
	global.__objectNames[694] = "obj_profile";
	global.__objectNames[695] = "obj_crystalorb";
	global.__objectNames[696] = "obj_hawmask";
	global.__objectNames[697] = "obj_DSM_control";
	global.__objectNames[698] = "obj_DSM_button";
	global.__objectNames[699] = "obj_DSM_level";
	global.__objectNames[700] = "obj_DSM_mario";
	global.__objectNames[702] = "obj_button_meteoritos";
	global.__objectNames[703] = "obj_btn_settings_hd";
	global.__objectNames[704] = "obj_bt_gb_edit";
	global.__objectNames[705] = "obj_nm_style_game";
	global.__objectNames[706] = "obj_nm_course_theme";
	global.__objectNames[707] = "obj_nm_historial";
	global.__objectNames[708] = "obj_nm_control";
	global.__objectNames[709] = "obj_nm_orden";
	global.__objectNames[710] = "obj_nm_button_big";
	global.__objectNames[711] = "obj_nm_reaccion";
	global.__objectNames[712] = "obj_nm_report";
	global.__objectNames[713] = "obj_nm_search_btn";
	global.__objectNames[714] = "obj_nm_input_text";
	global.__objectNames[715] = "obj_nm_dificultad";
	global.__objectNames[716] = "obj_nm_download";
	global.__objectNames[717] = "obj_nm_star";
	global.__objectNames[718] = "obj_nm_delete";
	global.__objectNames[719] = "obj_nm_search_id_btn";
	global.__objectNames[720] = "obj_btn_close_search";
	global.__objectNames[721] = "obj_nm_tiempo";
	global.__objectNames[722] = "obj_firebro";
	global.__objectNames[723] = "obj_firebro_res";
	global.__objectNames[724] = "obj_boomerangbro_res";
	global.__objectNames[725] = "obj_boomerangbro";
	global.__objectNames[726] = "obj_fireball_bro";
	global.__objectNames[727] = "obj_icebro";
	global.__objectNames[728] = "obj_icebro_res";
	global.__objectNames[729] = "obj_skewer";
	global.__objectNames[730] = "obj_skewer_res";
	global.__objectNames[731] = "obj_skewertrunk";
	global.__objectNames[732] = "obj_claw_res";
	global.__objectNames[733] = "obj_claw";
	global.__objectNames[734] = "obj_spike_ball_b";
	global.__objectNames[735] = "obj_spike_ball_b_res";
	global.__objectNames[736] = "obj_snow_ball_b";
	global.__objectNames[737] = "obj_parcarry";
	global.__objectNames[738] = "obj_snowball_bro";
	global.__objectNames[739] = "obj_player_goal_smb2";
	global.__objectNames[740] = "obj_frozenmario";
	global.__objectNames[741] = "obj_puller";
	global.__objectNames[742] = "obj_boomerang";
	global.__objectNames[743] = "obj_cinta";
	global.__objectNames[744] = "obj_cinta_on_res";
	global.__objectNames[745] = "obj_cinta_parent";
	global.__objectNames[746] = "obj_cinta_res";
	global.__objectNames[747] = "obj_cinta_switch";
	global.__objectNames[748] = "obj_meteorites_big";
	global.__objectNames[749] = "obj_meteorites";
	global.__objectNames[750] = "obj_meteorites_maker";
	global.__objectNames[751] = "obj_n64_snd_res";
	global.__objectNames[752] = "obj_bonus_snd_res";
	global.__objectNames[753] = "obj_n64_or";
	global.__objectNames[754] = "obj_efecto_musica_bonus";
	global.__objectNames[755] = "obj_boss_or";
	global.__objectNames[756] = "obj_bonus_or";
	global.__objectNames[757] = "obj_boss_snd_res";
	global.__objectNames[758] = "obj_shield_left";
	global.__objectNames[759] = "obj_link_arrow_anim";
	global.__objectNames[760] = "obj_link_dash_atack";
	global.__objectNames[761] = "obj_link_down_atack";
	global.__objectNames[762] = "obj_link";
	global.__objectNames[763] = "obj_link_arrow";
	global.__objectNames[764] = "obj_link_atack";
	global.__objectNames[765] = "obj_link_bomb";
	global.__objectNames[766] = "obj_link_res";
	global.__objectNames[767] = "obj_shield_right";
	global.__objectNames[768] = "obj_effect_link";
	global.__objectNames[769] = "obj_settings_custom";
	global.__objectNames[770] = "obj_settings_controls";
	global.__objectNames[771] = "obj_button_settings_close2";
	global.__objectNames[772] = "obj_boomboom_b_res";
	global.__objectNames[773] = "obj_boomboom_b";
	global.__objectNames[774] = "obj_chain_chomp_free_b";
	global.__objectNames[775] = "obj_shadow";
	global.__objectNames[776] = "obj_smoke";
	global.__objectNames[777] = "obj_SMB2_mushroom";
	global.__objectNames[778] = "obj_nm_refresh";
	global.__objectNames[779] = "obj_header";
	global.__objectNames[780] = "obj_btn_header_1";
	global.__objectNames[781] = "obj_btn_header_2";
	global.__objectNames[782] = "obj_btn_header_3";
	global.__objectNames[783] = "obj_btn_header_4";
	global.__objectNames[784] = "obj_cooligan";
	global.__objectNames[785] = "obj_cooligan_res";
	global.__objectNames[786] = "obj_goombrat_b_res";
	global.__objectNames[787] = "obj_galoomba2_b";
	global.__objectNames[788] = "obj_button_sombras";
	global.__objectNames[789] = "obj_yoshi_blue";
	global.__objectNames[790] = "obj_yoshi_runaway_blue";
	global.__objectNames[791] = "obj_egg_blue";
	global.__objectNames[792] = "obj_rails_res";
	global.__objectNames[793] = "obj_DSM_clouds";
	global.__objectNames[794] = "obj_DSM_control_game";
	global.__objectNames[795] = "obj_grrrol_new_res";
	global.__objectNames[796] = "obj_grrrol_b_res";

	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
