// Translate the Course World Tags
function scr_etiquetas_trad(argument0){
switch argument0{
	case "Tradicional": return scr_language(52);
	case "Puzles": return scr_language(53);
	case "Contrarreloj": return scr_language(54);
	case "Autoavance": return scr_language(55);
	case "Automatismos": return scr_language(56);
	case "Corto pero intenso": return scr_language(57);
	case "Competitivo": return scr_language(58);
	case "Tematico": return scr_language(59);
	case "Música": return scr_language(60);
	case "Artístico": return scr_language(61);
	case "Habilidad": return scr_language(62);
	case "Disparos": return scr_language(63);
    case "Contra jefes": return scr_language(64);
	case "En solitario": return scr_language(65);
	case "Standard": return scr_language(52);
	case "Puzzle-solving": return scr_language(53);
	case "Speedrun": return scr_language(54);
	case "Autoscroll": return scr_language(55);
	case "Auto-Mario": return scr_language(56);
	case "Short and Sweet": return scr_language(57);
	case "Short and sweet": return scr_language(57);
	case "Multiplayer Versus": return scr_language(58);
	case "Themed": return scr_language(59);
	case "Music": return scr_language(60);
	case "Art": return scr_language(61);
	case "Technical": return scr_language(62);
	case "Skill": return scr_language(62);
	case "Shooter": return scr_language(63);
	case "Boss battle": return scr_language(64);
	case "Single player": return scr_language(65);
	case "Puzzles":  return scr_language(53);
	case "Contra-relógio": return scr_language(54);
	case "Avanço automático": return scr_language(55);
	case "Automáticos": return scr_language(56);
	case "Curto porém intenso": return scr_language(57);
	case "Temático": return scr_language(59);
	case "Habilidade": return scr_language(62);
	case "Contra chefes": return scr_language(64);
	case "Sozinho": return scr_language(65);
	case "Classico": return scr_language(52);
	case "Rompicapi": return scr_language(53);
	case "Corsa": return scr_language(54);
	case "Scorrimento": return scr_language(55);
	case "Automatico": return scr_language(56);
	case "Corto ma bello": return scr_language(57);
	case "Competizione": return scr_language(58);
	case "Musica": return scr_language(60);
	case "Artistico": return scr_language(61);
	case "Tecnico": return scr_language(62);
	case "Sparatutto": return scr_language(63);
	case "Scontro col boss": return scr_language(64);
	case "Un giocatore": return scr_language(65);
	case "标准": return scr_language(52);
	case "解谜": return scr_language(53);
	case "计时挑战": return scr_language(54);
	case "自动卷轴": return scr_language(55);
	case "自动马力欧": return scr_language(56);
	case "一次通过": return scr_language(57);
	case "多人对战": return scr_language(58);
	case "机关设计": return scr_language(59);
	case "音乐": return scr_language(60);
	case "美术": return scr_language(61);
	case "技巧": return scr_language(62);
	case "射击": return scr_language(63);
	case "对战BOSS": return scr_language(64);
	case "单打": return scr_language(65);
    case "Link": return "Link";
	case "---":  return "---";
}
}